#+TITLE: Bios Editing in Zambia
#+EMAIL: NELA.Percy@gmail.com
#+AUTHOR: Percy
#+DATE: November 2011
#+DESCRIPTION: Zambia is a piece of Conference Management Software.  This document is a "How To" guide to editing the various bios type entries for the Zambia FFF-branch instance for your conference.  This is still a work in progress.
#+MACRO: DESCRIPTION Zambia is a piece of Conference Management Software.  This document is a "How To" guide to editing the various bios type entries for the Zambia FFF-branch instance for your conference.  This is still a work in progress.
#+KEYWORDS: Zambia, Documentation, FFF branch
#+META: KEYWORDS Zambia, Documentation, FFF branch
#+META: Silly This is just silly
#+LANGUAGE: en
#+OPTIONS: \n:nil ^:nil timestamp:nil creator:nil H:3 num:3 toc:nil @:t ::nil |:t -:t todo:nil tasks:nil tags:nil <:t *:t author:t email:t skip:nil d:t f:t pri:t
#+STARTUP: fninline
#+SETUPFILE: "Headers/setupfile.org"
#+INCLUDE: "Headers/include.org"
#+TOC: headlines 3
#+LaTeX: \listoftables
#+LaTeX: \newpage
#+LaTeX: \pagenumbering{arabic}
* Introduction

  The biographical information for your presenters is an important
  part of the convention experience that Zambia manages.  This is part
  of how people decide they want to attend your convention and part of
  what they might want to do when there.  From a presenter's point of
  view, the biographical information is a way to connect with their
  fan-base, to allow contact, give information, or arrange for
  continued interactions.  From a con manager's point of view,
  managing biographical information is fairly work-intensive, and one
  of the things that doesn't exactly scale.

  There are several pieces that make up the biographical information
  matrix within Zambia.  Few, any, or all of the elements can be
  chosen to be deployed and customized to the desire of your
  particular convention or set of conventions.  Currently the
  biographical information is designed to be held in a shared
  database, which lies outside of a specific convention, so that,
  while the information is available and editable within that
  convention, when the information is updated, it is updated across
  all the conventions served from the same server.  Therefore the
  updated information is available across multiple convention
  instances.  Not all of the conventions will necessarily use all of
  the information.
* Biographical Information Matrix

  The biographical information Matrix is made up of four different
  values.  They are the types of biographical information, the status
  of a biographical element, the destination for the biographical
  element, and the language that that element is written in.  There
  are limits applied to the various sizes of the entries, governed by
  the PublicationsLimits table.
** Types

   The (extendable) types that are currently in use are:
   + uri: The set of Uniform Resource Identifiers (URLs, URNs, etc)
     that are available on your Zambia site, for people to follow.
     Most HTML markup works with this type.  Examples include mailto
     references and webiste references.
   + bio: The written biographical descriptive information.
   + name: The name to be used in each circumstance
   + pronoun: The preferred pronoun.
   + twitter: A series of white-space separated twitter addresses.
   + facebook: A series of white-space separated Facebook addresses.
   + fetlife: A series of white-space separated FetLife addresses.
** States

   The states that are currently in use are used as a flow for the
   information and communication around such.
   + raw: This is the information provided by or updated by the
     presenter when they have been granted access to Zambia.  They
     might update this, and that will show as differences between this
     state and the "edited" state and/or the "good" state.  This
     allows for unknown people to put unknown references and
     information on your web-site.  Beware.
   + edited: This is intended to be the mid-step, the negotiation
     point between the people responsible for what is being published
     in the literature and on the web, and the individual presenters,
     it is presented to facilitate dialogue, and everyone can see how
     it is to be presented, should it be approved.  Once the "edited"
     state and the "raw" state are in agreement due to the
     collaboration between the staff and the participant, it would be
     considered ready for promotion to the "good" state.
   + good: This is what is slated to be published.  Once the "edited"
     state information matches the "raw" state information, that bio
     element should be promoted to the "good" state. If further
     changes to the "raw" state information happen, because a
     participant has edited the information, the process begins again.
     various publishing media.
** Destinations

   The possible destinations for each of the types, determines where
   that particular information is going to be used.  Each of the
   limits set in the PublicationLimits table is both Type and
   Destination keyed, so, for example, the limit for the information
   published on the web might be more verbose (or in a different
   format) than that published on the badge, or in the con hard copy
   publications.
   + web: To be published on the web, on the larger website, and in
     the KonOpas subset, if that is chosen to be used.
   + book: To be published in a hard copy format, a book, a pamphlet,
     or the like about the con.
   + badge: To be published on a name-badge type object, so that a
     subset of the information is immediately available at a glance.
   + staffweb: As for the web, but for staff bios, which might be
     different from present or vending bios.
   + staffbook: Similar to staffweb, for the staff bios which might be
     different from presenting or vending bios.
** Languages

   The language field is designed to contain any of the various
   language elements.  Currently en-us and fr-ca are the two expected
   ones, as a hold-over from the original "secondary language" concept
   of Zambia when it was used for a Canadian event.  Starting any
   language will allow it to be flexible enough to have it show up in
   the appropriate tables.  Just adding to the LANGUAGE_LIST searches
   for each/all of the languages listed.  While this is a first step
   in the internationalization of this software, expanding the rest,
   along these lines is expected and planned for.  Each of the other
   elements, the various verbiage on the pages, and in the reports
   will pull from similar tables, able to be customized off of, or
   feed concurrently, depending on the design the multiple languages
   available.  All of the biographical information is designed to be
   subsequently displayed, rather than switched on the
   $_SESSION['language'] variable.
* Pages
** StaffManageBios.php
#+LaTeX: \label{StaffManageBios.php}
#+HTML: <A NAME="StaffManageBios.php" ID="StaffManageBios.php"></A>
#+LaTeX: \underline{
   [[../webpages/StaffManageBios.php][StaffManageBios.php]]
#+LaTex: }

   This is the starting point for managing the biographical and
   descriptive information data that will be published.  The specific
   grids are:
   + the presenters
   + the staff
   + the schedule elements
   + the volunteers
   + the vendors

   Each of the tables on this page (illustrated below) address
   different sets of information.  There might be some overlap, for
   example a staff member might also be a vendor, or a presenter, so
   information might be accessible via several paths.  Every table
   cell will allow you to click through, and address whatever
   biographical elements need updating.

   The rows are organized around the states with the first three rows
   indicating missing entries for the "raw" state the would appear in
   the first row, or missing elements in the "edited" state or "good"
   state that exist in the "raw" state in the second and third.  The
   fourth through sixth rows are comparisons to find which elements
   don't match.  The fourth row being if the "raw" state elements and
   the "edited" state elements don't match. The fifth a comparison
   between the "raw" state and "good" state.  The sixth being between
   the "edited" state and the "good" state. Then, the final row is for
   if everything across all the states match each other.  The goal is
   to achieve everything listed in the final row.

   The columns are a combination of the various languages available
   and the types and destinations of each element.

   To bring up the list of individuals in any particular category of
   missing, incorrect, or even correct information, simply click on
   the number of elements in the state you wish to work with.  In the
   example below, there are seven individuals who do not have an
   edited en-us web entry in the biographical information matrix.  By
   clicking on the "7" in that section of the table, you bring up the
   list of participants who's elements need editing.

   The table might resemble the following:
#+CAPTION: Staff - Manage Participant Biographies
#+LABEL: tbl:staffmanageparticipantbiographies
#+ATTR_LaTeX: longtable width=\textwidth align=|c|c|c|c|c|c|c|c|c|
#+ATTR_HTML: border="1" rules="all" frame="all"
|-----------------------------------+----------------+----------------+-----------------+-----------------+---------------+---------------+----------------+----------------|
| Count of the States of the bios   | en-us name web | fr-ca name web | en-us name book | fr-ca name book | en-us web uri | fr-ca web uri | en-us book uri | fr-ca book uri |
|-----------------------------------+----------------+----------------+-----------------+-----------------+---------------+---------------+----------------+----------------|
| Missing raw bio                   |                |                |               3 |               6 |            59 |            61 |             14 |             61 |
| Missing edited bio                |              7 |             16 |              21 |               5 |            48 |            61 |             14 |             61 |
| Missing good bio                  |             59 |             59 |              59 |              59 |            59 |            61 |             14 |             61 |
| Raw bio doesn't match edited bio  |             17 |             11 |              18 |              19 |             9 |               |                |                |
| Edited bio doesn't match good bio |             12 |              9 |              28 |              46 |             9 |               |                |                |
| All bios match                    |              5 |              3 |               4 |                 |               |            61 |             47 |             61 |
|-----------------------------------+----------------+----------------+-----------------+-----------------+---------------+---------------+----------------+----------------|

   Once the particular subsection for editing has been picked, you
   will be provided with a list of names in this category, so you
   might choose the one(s) to be edited.  Illustrated below.

   The three columns in this table are:
   + Participant: Each name in this column is a link that will bring
     you to the page referenced by section [[StaffEditBios.php]] for the
     individual chosen, so the "edited" state can be updated.  Also
     from here is where the information might be promoted to the
     "good" state if everything is in agreement.
   + Edit Full: Each name in this column is a link that will bring you
     to the page referenced by section [[StaffEditCreateParticipant.php]]
     to edit the "raw" state of the information on the participant
     chosen. This is the full information we have on an individual, in
     case that such information is necessary to find out more about
     who they are, or if there are any notes, or the like to assist
     you with the biographical information editing.
   + Currently being edited by: This column indicates the individual
     who is the one editing the particular individual's information at
     this time.  Please, do not choose to edit the biographical
     information of someone who is locked by someone other than you.

   The table might resemble the following:
#+CAPTION: Staff - Manage Participant Biographies Subedit
#+LABEL: tbl:staffmanageparticipantbiographiessubedit
#+ATTR_LaTeX: longtable width=\textwidth align=|l|l|l|l|
#+ATTR_HTML: border="1" rules="all" frame="all"
|-------------+-------------+---------------------------|
| Participant | Edit Full   | Currently being edited by |
|-------------+-------------+---------------------------|
| Mr E.       | Mr E.       |                           |
| Joker       | Joker       | Str8mn                    |
| Batman      | Batman      | The Riddler               |
| The Riddler | The Riddler | Batman                    |
| Catwoman    | Catwoman    |                           |
| Cartman     | Cartman     |                           |
| Robin       | Robin       |                           |
|-------------+-------------+---------------------------|

   There is also the "return" link, just above the table, that brings
   you back to the page referenced by the table [[tbl:staffmanageparticipantbiographies]["Staff - Manage
   Participant Biographies"]], in case you are done with this particular
   subset of individuals, and wish to deal with others.
** StaffEditBios.php
#+LaTeX: \label{StaffEditBios.php}
#+HTML: <A NAME="StaffEditBios.php" ID="StaffEditBios.php"></A>
#+LaTeX: \underline{
   [[../webpages/StaffEditBios.php][StaffEditBios.php]]
#+LaTex: }

   This page is where an individual's information is edited from the
   point of view of the con staff.  Once this page is opened for a
   participant, the editing individual's name will be placed in the
   "Currently being edited by" column, so two people don't try to edit
   the same bio information at the same time.

   There are two links at the top of the page.  The first is the
   individuals name and will lead you to the page mentioned section
   [[StaffEditCreateParticipant.php]], in the mode of editing the
   participant chosen, and the return link, which will bring you back
   to the table above on the page from section [[StaffManageBios.php]].

   Any of the "Save Whole Page" buttons will save the current state of
   the entire page, and clear the "Currently being edited by" flag.

   The "Promote ... to good." links will only show up if the "raw"
   state information matches the "edited" state information.

   The "Good entry exists for ... Biography" informational statement
   is there to let you know that the information has been promoted all
   the way up to the "good" state at least once before.

   The design of this page has a series of elements, alternating "raw"
   state and "edited" state boxes, with the "raw" state boxes there
   for copying purposes, for they are not malleable.  Which entries
   are available are dependent on what access the individual has.  The
   ordering of the elements on the page will be something like:
   + raw uri book en-us
   + edited uri book en-us
   + raw uri book fr-ca
   + edited uri book fr-ca
   + raw uri web en-us
   + edited uri web en-us
   + raw uri web fr-ca
   + edited uri web fr-ca
   + raw bio book en-us
   + edited bio book en-us
   + ...

   There might be style guide for the formatting of the information in
   each of the informational entries.  Things like:
   - Each of the web and book bios entries are pre-pended
     automatically with the web and book name entries, bios should be
     written in the third person, and start with a space character.
   - Multi-entry web uri entries should be separated by a web-style
     line-break.
   - Multi-entry book uri entries should be separated by a
     double-colon

   The database is (by default) a Latin-8 character set, so anything
   in the entries that is outside of that character set, will, most
   probably either be replaced by "?" or break the entry.

   Entries into the blocks can be as long as you like, but, they will
   be length-checked, and rejected if they are longer than the limits
   set by the PublicationLimits table.
** StaffEditCreateParticipant.php
#+LaTeX: \label{StaffEditCreateParticipant.php}
#+HTML: <A NAME="StaffEditCreateParticipant.php" ID="StaffEditCreateParticipant.php"></A>
#+LaTeX: \underline{
   [[../webpages/StaffEditCreateParticipant.php?action=edit][StaffEditCreateParticipant.php]]
#+LaTex: }

   While this page is of more general use (which is more fully
   documented in the Presenter Flow Document) if absolutely necessary
   it can be used to modify the raw biographical information. The raw
   state of all of the types (uri, facebook, bio, etc.), destinations
   (web, book, badge, etc.), and languages are available to be edited
   on this page.
