#+TITLE: Email Functions in Zambia
#+EMAIL: NELA.Percy@gmail.com
#+AUTHOR: Percy
#+DATE: June 2015
#+DESCRIPTION: Zambia is a piece of Conference Management Software.  This document is a "How To" guide to using the Email Functions in the Zambia FFF-branch instance for your conference.  This is still a work in progress.
#+MACRO: DESCRIPTION Zambia is a piece of Conference Management Software.  This document is a "How To" guide to using the Email Functions in the Zambia FFF-branch instance for your conference.  This is still a work in progress.
#+KEYWORDS: Zambia, Documentation, FFF branch
#+MACRO: KEYWORDS Zambia, Documentation, FFF branch
#+LANGUAGE: en
#+OPTIONS: \n:nil ^:nil timestamp:nil creator:nil H:3 num:3 toc:nil @:t ::nil |:t -:t todo:t tasks:t tags:t <:t *:t author:t email:t skip:nil d:t f:t pri:t
#+STARTUP: fninline
#+SETUPFILE: "Headers/setupfile.org"
#+INCLUDE: "Headers/include.org"
#+TOC: headlines 2
#+TODO: TODO(t) MYQA(m) VENDORQA(v) | DONE(d)
#+LaTeX: \newpage
#+LaTeX: \pagenumbering{arabic}
* General Design

  This is a working guide on how to use the Email portion of Zambia.
* Components

  There are several components to the emailing system in Zambia.
  - To lists
  - From/CC addresses
  - Composing email
  - "Mail Merge" style replacements
  - Sending the email
* "To" lists

  The "To" lists are maintained in the database, as a query.  Many
  queries have been pre-loaded, but you might want to customize or
  build your own.  To do so, there is a good report, and a functional
  tool to help.  The report is on the page:

#+LaTeX: \label{genreport.php?reportname=emailtolist}
#+HTML: <A NAME="genreport.php?reportname=emailtolist" ID="genreport.php?reportname=emailtolist"></A>
#+LaTeX: \underline{
  [[../webpages/genreport.php?reportname=emailtolist][genreport.php?reportname=emailtolist]]
#+LaTex: }

  That will either allow you to edit an existing list, or create a new
  list.  That uses the page:

#+LaTeX: \label{StaffEmailToUpdate.php}
#+HTML: <A NAME="StaffEmailToUpdate.php" ID="StaffEmailToUpdate.php"></A>
#+LaTeX: \underline{
  [[../webpages/StaffEmailToUpdate.php][StaffEmailToUpdate.php]]
#+LaTex: }

  This page is used to appropriately create or change the query that
  produces the "To" line, and a few other little bits along the way.
  There is a link to it at the top of the report referenced above.

  The query needs to produce the following fields:
  + badgeid
  + firstname
  + lastname
  + email
  + pubsname
  + badgename
  + interestedtypename as itn

  If you are not really concerned with the interestedtypename (which
  defaults to checking on "Yes") just use concat("Yes") as itn for it.
  Everything else should exist on all people in the database.  It is
  suggested that at least one test email address is set up as the
  first entry, to test the system and be the default "To:" list in
  case it was forgotten to be set.  Having a test address is good
  being that the email process from within Zambia depends on software
  outside Zambia to work, and therefore might not work right from the
  start.
* From/CC

  These are generated from those who have roles this year in the con.
* Composing email

  This is a two-step process.  One is writing the email, with all the
  attendant information, and the other is checking it to make sure it
  does the right thing.

  The first is accomplished from the page:

#+LaTeX: \label{StaffSendEmailCompose.php}
#+HTML: <A NAME="StaffSendEmailCompose.php" ID="StaffSendEmailCompose.php"></A>
#+LaTeX: \underline{
  [[../webpages/StaffSendEmailCompose.php][StaffSendEmailCompose.php]]
#+LaTex: }

  This should be available under the "Manage Participants & Schedule"
  tab.  If it is not available to you, it might be that you have not
  (yet) been authorized to use the email program.  Please check with
  your Zambia administrator for further information.

  Once on this page, you can set your To:, From:, CC:, Subject:, and
  Body of the email.

  If it is a long, or complex email, it is suggested that you compose
  it in another editor, and then paste it into the box on this page.
  Although, be careful, this is limited to the Latin-8 set of
  characters, so other characters (like special quotes, apostrophes,
  etc) will not translate well, if they are in there at all.  (Yes,
  this is a bug, and needs to be tracked down and fixed.)

  Once the email is written, hit the "See it" button (not the "Reset"
  button) and it will take you to the next step.

  The next page will list all the recipients in the top box.  If
  they do not match your expectations, you might have open a fresh
  window or tab to go to the page:

#+LaTeX: \label{StaffEmailToUpdate.php}
#+HTML: <A NAME="StaffEmailToUpdate.php" ID="StaffEmailToUpdate.php"></A>
#+LaTeX: \underline{
  [[../webpages/StaffEmailToUpdate.php][StaffEmailToUpdate.php]]
#+LaTex: }

  to tweak the "To:" query some more.  Use the "Go Back" button, so
  you don't lose your words, and tweak the query in the other window
  or tab, and then move forward again with the "See it" button.

  The first individual on the list will have their letter in the lower
  box.  Check the letter to make sure it reads the way you wish.  If
  it does, hit "Send".  If it does not, or you need to go back to fix
  the "To:" field, use the "Go Back" button.

  NOTE: Using the "Go Back" button resets the "From:" and "CC:"
  fields, so make sure you set them appropriately, if you use the "Go
  Back" button.
* "Mail Merge" style replacements

  There are a number of things you can replace in your email so they
  are specific to the person.  They currently are:
  +  $ BADGEID $ 
  +  $ FIRSTNAME $ 
  +  $ LASTNAME $ 
  +  $ EMAILADDR $ 
  +  $ PUBNAME $ 
  +  $ BADGENAME $ 
  +  $ SCHEDULE $ 
  +  $ FULLSCHEDULE $ 
  +  $ BIOS $ 
  +  $ LIAISON $ 
  +  $ HOTELROOM $ 
  +  $ ENTRANCES $ 
  +  $ CONFIRMNUM $ 

  They are pulled from a number of sources, so they might not work
  as you fully expect them to, but they basically pull what they
  describe from the database to populate the letter.
  As an example, if you start your email with:
#+BEGIN_SRC
  "Hello $PUBSNAME$,"
#+END_SRC
  it will cycle in each of the individual's
  pubsname in place of $ PUBSNAME $.  Same with all the other
  replace-tags.
* Sending the email

  The "Send it" button doesn't actually send the email.  We've had a
  few problems with people thinking our email is spam, so there are
  two ways to get the email sent.  Either via the bulk sender, which
  sends a chunk of them at a time, automatically, or you can use the:

#+LaTeX: \label{HandSendQueuedMail.php}
#+HTML: <A NAME="HandSendQueuedMail.php" ID="HandSendQueuedMail.php"></A>
#+LaTeX: \underline{
  [[../webpages/HandSendQueuedMail.php][HandSendQueuedMail.php]]
#+LaTex: }

  This will call up each email individually in your local email
  sending program, so you can check/modify each one before sending,
  and make sure each email is individually sent. Since you
  individually "mark as sent" each potential email, if you want to
  mark one as sent, but not actually send it, you can. This is useful
  if an address was included accidentally, for example. The hand
  sending process gives you finer control over what goes out.

  The bulk emailer currently is only available to the Zambia
  maintainer, due to errors and difficulties from the users.  If you
  wish them just to be send on the schedule, please let your Zambia
  maintainer know to kick off the process.
