#+TITLE: Notes for Coders
#+EMAIL: NELA.Percy@gmail.com
#+AUTHOR: Peter
#+DATE: March 2010
#+DESCRIPTION: Zambia is a piece of Conference Management Software.  This document is a general guide assisting in the way of programming the Zambia FFF-branch, as inhereted from the main branch.
#+KEYWORDS: Zambia, Documentation, FFF branch
#+LANGUAGE: en

#+OPTIONS: \n:t ^:nil timestamp:nil creator:nil H:3 num:t @:t ::nil |:t -:t todo:nil tasks:nil tags:t <:t *:t author:t email:t skip:nil d:t f:t pri:t
#+LATEX_CLASS: koma-article
#+LaTeX_CLASS_OPTIONS: [tablesignature] 
#+LATEX_HEADER: \usepackage{booktabs}
#+LATEX_HEADER: \usepackage[scaled]{beraserif}
#+LATEX_HEADER: \usepackage[scaled]{berasans}
#+LATEX_HEADER: \usepackage[scaled]{beramono}
#+LATEX_HEADER: \usepackage[usenames,dvipsnames]{color}
#+LATEX_HEADER: \usepackage{fancyhdr}
#+LATEX_HEADER: \usepackage{subfig}
#+LaTeX_HEADER: \usepackage{listings}
#+LaTeX_HEADER: \lstnewenvironment{common-lispcode}
#+LaTeX_HEADER: {\lstset{language={HTML},basicstyle={\ttfamily\footnotesize},frame=single,breaklines=true}}
#+LaTeX_HEADER: {}
#+LATEX_HEADER: \usepackage{paralist}
#+LATEX_HEADER: \let\itemize\compactitem
#+LATEX_HEADER: \let\description\compactdesc
#+LATEX_HEADER: \let\enumerate\compactenum
#+LATEX_HEADER: \usepackage[letterpaper,includeheadfoot,top=12.5mm,bottom=25mm,left=19mm,right=19mm]{geometry}
#+LATEX_HEADER: \pagestyle{fancy}
#+LaTeX: \pagenumbering{roman}
#+LaTeX: \thispagestyle{fancy}
#+LaTeX: \renewcommand{\headrulewidth}{0pt}
#+LaTeX: \renewcommand{\footrulewidth}{1pt}
#+LaTeX: \lhead{}
#+LaTeX: \rhead{}
#+LaTeX: \chead{}
#+LaTeX: \lfoot{{{{{AUTHOR}}}} <{{{{EMAIL}}}}>}
#+LaTeX: \cfoot{}
#+LaTeX: \rfoot{\thepage}
#+LaTeX: \begin{abstract}
#+LaTeX: \vspace{5cm}
#+LaTeX: {\LARGE{\textbf{Abstract:\\}}}
{{{DESCRIPTION}}}
#+LaTeX: \end{abstract}
#+HTML:<h2>Abstract:<br></h2><p>{{{DESCRIPTION}}}</p>
#+LaTeX: \newpage
#+LaTeX: \renewcommand{\headrulewidth}{1pt}
#+LaTeX: \chead{{{{{TITLE}}}}}
#+LaTeX: \tableofcontents
#+LaTeX: \listoftables
#+LaTeX: \listoffigures
#+LaTeX: \newpage
#+LaTeX: \pagenumbering{arabic}
* Files
We need consistency, so here is the plan:
** contains configuration information that each conference should set: Local/db_name.php

** contains css information: Common.css  ParticipantSection.css  StaffSection.css

** auto generated files that display a page (aka you can link to them)
   lowercasewithnounderscores.php
   *No Longer Used!*

** contains functions and constants that other pages use (not autogenerated)
   lower_with_underscore_functions.php
   db_functions.php           # for database related functions
   data_functions.php
   validate_functions.php
   render_functions.php

** file that displays a page and can be linked to  (not autogenerated) 
   StrongCaps.php
   BrainstormStrongCaps.php    # for brainstorm pages
   StaffStrongCaps.php    # for staff only pages
   ParticipantStrongCaps.php    # for Participant only pages
   CommonStrongCaps.php    # pages used by at least 2 different groups

** file that processes a post operation, but calls a separate file to 
   display the results (deprecated?)
   SubmitStongCaps.php

** file that processes a post operation and display the results 
   (often by calling a function that is elsewhere)
   StrongCaps_POST.php

** file that contains functions used by a page of the same name
   (and not elsewhere.   If it is used elsewhere it needs to move)
   StrongCaps_FNC.php

** shell script for report generation: gencsv.sh genindex.sh genreports.sh
* Interesting hacks
** Presenter only
   To end up with either a blank, or just the presenter (no aidedecamp, introducer, or volunteer) in a group_concat use:
   group_concat(if(volunteer=0 and introducer=0 and aidedecamp=0,pubsname,NULL) SEPARATOR " - ") AS 'Participants' or
   group_concat(if(volunteer=0 and introducer=0 and aidedecamp=0,pubsname,NULL), if(moderator=1,' (M)','') order by moderator DESC, pubsname SEPARATOR " - ") AS 'Participants'
   It's much easier and cleaner than doing the whole sub-SELECT thing, or limiting it with:
   volunteer=0 AND introducer=0 AND aidedecamp=0
   group_concat(' ',P.pubsname, if(moderator=1,'  (M)','') order by moderator, pubsname
** Duration
   This is what we have standardized on for the duration printing:
    CASE
      WHEN HOUR(duration) < 1 THEN
        concat(date_format(duration,'%i'),'min')
      WHEN MINUTE(duration)=0 THEN
        concat(date_format(duration,'%k'),'hr')
      ELSE
        concat(date_format(duration,'%k'),'hr ',date_format(duration,'%i'),'min')
      END AS Duration,
** Time compare
   time_to_sec(starttime) < time_to_sec("19:30:00") compares two times.
** Row count
   select @rownum:=@rownum+1 AS "Order", title from Sessions, (SELECT @rownum:=0) AS R
   or with more complexity, and applicability:
   concat("<INPUT type=\"checkbox\" name=\"del",@rownum:=@rownum+1,"\" value=\"1\">\n<INPUT type=\"hidden\" name=\"row",@rownum,"\" value=\"",scheduleid,"\"><INPUT type=\"hidden\" name=\"rowsession",@rownum,"\" value=\"",sessionid,"\">") AS "Delete",
** Previous con
   LEFT JOIN (SELECT
                  GROUP_CONCAT(conid, " - ", interestedtypename) AS previous,
	          badgeid
	        FROM
	            $ReportDB.Interested
                  JOIN $ReportDB.InterestedTypes USING (interestedtypeid)
                WHERE
                   conid!=$conid
                 GROUP BY
                    badgeid) PV USING (badgeid)
** Alternate Roles
    LEFT JOIN (SELECT
                   email,
                   GROUP_CONCAT("<A HREF=StaffEditCreateParticipant.php?action=edit&partid=",badgeid,">",permrolename,"</A>" SEPARATOR ", ") AS altrole
                 UMFRAY
                     $ReportDB.UserHasPermissionRole
                   JOIN $ReportDB.PermissionRoles USING (permroleid)
                   JOIN $ReportDB.CongoDump USING (badgeid)
                 WHERE
                   conid=$conid AND
                   permrolename NOT IN ('Vendor')
                 GROUP BY
                   badgeid) AR USING (email)
** Multi-select boxes
   need the specail "close" button to work (from the javascript file)
   as well as the mapping to a multi-box, and the "src" and "dest" set
   up properly.  All expect the conid now, so that has to be ported.
   The "SessionHas" can be in either for the nonce.  Check the
   db_functions and the data_functions files as well, to make sure
   those are going to work.
