#+TITLE: Panelists Guide for Zambia
#+EMAIL: NELA.Percy@gmail.com
#+AUTHOR: Percy
#+DATE: March 2012
#+DESCRIPTION: Zambia is a piece of Conference Management Software.  This document is a "How To" guide assisting panelists in the use of the Zambia FFF-branch instance for your conference.  This is still a work in progress.
#+MACRO: DESCRIPTION Zambia is a piece of Conference Management Software.  This document is a "How To" guide assisting panelists in the use of the Zambia FFF-branch instance for your conference.  This is still a work in progress.
#+KEYWORDS: Zambia, Documentation, FFF branch
#+META: KEYWORDS Zambia, Documentation, FFF branch
#+LANGUAGE: en
#+OPTIONS: \n:nil ^:nil timestamp:nil creator:nil H:3 num:3 toc:nil @:t ::nil |:t -:t todo:nil tasks:nil tags:nil <:t *:t author:t email:t skip:nil d:t f:t pri:t
#+STARTUP: fninline
#+SETUPFILE: "Headers/setupfile.org"
#+INCLUDE: "Headers/include.org"
#+TOC: headlines 3
#+LaTeX: \newpage
#+LaTeX: \pagenumbering{arabic}
* Introduction

  Zambia is the system used by this convention to organize and
  schedule our content.  Logging into Zambia as a participant allows
  panelists to indicate which panels they would like to be on, set
  their availability during the convention and create a
  profile/biography.
* First login/Welcome
#+LaTeX: \label{welcome.php}
#+HTML: <A NAME="welcome.php" ID="welcome.php"></A>
#+LaTeX: \underline{
  [[../webpages/welcome.php][Welcome]]
#+LaTex: }

  The first page you see, when you log in will have a lot of
  important, and general information on it.  Please read it, and let
  your liaisons know if you have any issues.

* My Profile
#+LaTeX: \label{my_contact.php}
#+HTML: <A NAME="my_contact.php" ID="my_contact.php"></A>
#+LaTeX: \underline{
  [[../webpages/my_contact.php][My Profile]]
#+LaTex: }

  When you log in for the first time, you will need to update your
  profile and change your password away from the default, or the
  password sent upon reset. This can be done by clicking "profile" on the menu bar.

  From this page you can do the following:
  + Let us know if you are interested and able to participate in
    programming for the upcoming convention:
    + If you want to be on panels or otherwise be a program
      participant, set it to "Yes".
    + If you are unable to attend this event, but want to be invited
      for future events, please still log in and set it to "No".
  + Let us know if we can share your e-mail address with other
    participants.  Please consider saying yes, so that moderators of
    the panels you have been selected for can contact you prior to the
    convention to let you know their format, so you can discuss and
    prep for the panel.  Saying no will not affect our decisions when
    making panelist selections for the panels.
  + Let us know if we can photograph you while you are participating
    on the panels, and if we can use those images in the promotion of
    the convention.  Saying no will not affect our decisions when
    making panelist selections for panels.
  + Let us know how you want your name and other bio information to
    appear in our electronic and print publications.  If you have
    questions about this, please contact your liaison.  This
    information will be presented, with what we currently have for
    you, and gives you space to change it.  When and if you change
    your bios information, either your liaison, or a bios editor might
    be in touch, if there is any further changes we might suggest.
  + Review the contact information we have for you.
* My Availability
#+LaTeX: \label{my_sched_constr.php}
#+HTML: <A NAME="my_sched_constr.php" ID="my_sched_constr.php"></A>
#+LaTeX: \underline{
  [[../webpages/my_sched_constr.php][My Availability]]
#+LaTex: }

  Next, please let us know about the times you are available to be on
  panels, and the number of panels you are willing to be on, by
  selecting the "availability" option from the menu in the page
  header. This allows us to get an idea of what kind of schedule you
  would like to have during the convention. In addition to listing
  time ranges, make sure to enter information on any constraints or
  conflicts that might occur on your schedule at the bottom of the
  page. Be as thorough as you can and fill out all fields on this page
  -- the more information we have, the better! Please keep in mind
  that a narrow availability listing makes it difficult for our staff
  to schedule you, so please be both honest and realistic about your
  con participation time!
* Search Panels
#+LaTeX: \label{my_sessions1.php}
#+HTML: <A NAME="my_sessions1.php" ID="my_sessions1.php"></A>
#+LaTeX: \underline{
  [[../webpages/my_sessions1.php][Search Panels]]
#+LaTex: }

  Next up is "Search Panels"; this is how you find out what sort of
  panels and other program items are available for
  participation. Because of the volume of selections that are
  available at this convention, we organize panels by tracks. There
  are no restrictions on how many tracks a person can participate on;
  we love panelists that have knowledge in several content areas and
  can participate on a diverse range of items!

  From the "Search Panels" page you can do the following:
  + Click the drop menu on the "Track" option. This will show you a
    list of all our tracks or if there is a specific panel number that
    can be selected as well.
  + Once you have made your selections, click "Search". This will give
    you a list of panel options that match your selection.
  + Each entry has a box next to the title that you click on to add it
    as a panel you are interested in participating in.
  + Once you have made your selections, click "Save". You will be taken
    to a page where you can enter a rating and give reasons as to why
    you would be a good choice for a given panel (see the section
    [[My Panel Interests]] below).
  + Go back to the "Search Panels" page to add more panels to your
    list, either from the same track, or other tracks.
* My Panel Interests
#+LaTeX: \label{PartPanelInterests.php}
#+HTML: <A NAME="PartPanelInterests.php" ID="PartPanelInterests.php"></A>
#+LaTeX: \underline{
  [[../webpages/PartPanelInterests.php][My Panel Interests]]
#+LaTex: }

  Once you have selected a bunch of panels you are interested in
  participating in, it is time to provide us with information for why
  we should place YOU on that panel.  This is a really important step!
  We have so many great panelists that sign up each event, so we rarely
  assign people to panels who have not ranked the panel and given
  reason as to why they would be a fabulous addition to this panel.

  Click on the "My Panel Interests" option from the menu to view all
  the panels you have previously selected.
  + First, go through and rank all your panel selections. We use the
    following rating system:
    + 1 -- Oooh! Oh! Pick Me!
    + 2-3 -- I'd like to if I can.
    + 4-5 -- I am qualified but this is not one of my primary
      interests.
    You are limited to 4 sessions each of preferences 1-4 and there is
    no limit to the number of sessions for which you can express
    preference 5.
  + Next, for each panel, write in the text boxes to let us know
    why you would be fabulous on that session.
    + Completing this step thoughtfully is especially important for
      the items you rank highest.
    + Address anything asked of panelists in the beige box associated
      with that panel.
    + This does not need to be long -- a short paragraph is typical.
    + Some panelists draft these out in a separate document and then
      cut-and-paste their entries into Zambia as a final step.
    + If you do not fill this section out, you might not get placed on
      the panel, even if you rate it a 1 and feel that you are an
      obvious choice.
  + If you are interested in moderating a particular panel, please
    select that option while providing your rankings.  The panelists
    most enthusiastic about a topic do not always make the best
    moderators, as moderators are facilitators in addition to
    contributors on a panel. So keep this in mind when ranking and
    indicating your interest in moderating.
  + Remember to save your progress approximately every ten minutes, so
    that you are not logged out due to inactivity and lose your
    selections or what you wrote!
  + Ranking a panel as "1" and writing a thesis on why you are perfect
    for the panel does not guarantee your placement on it. Most of our
    panels have more qualified people sign up for them than we have
    spaces on the panel (typically 4-5), and there are more sessions
    to sign up for than we have spots in the schedule.
* My General Interests
#+LaTeX: \label{my_interests.php}
#+HTML: <A NAME="my_interests.php" ID="my_interests.php"></A>
#+LaTeX: \underline{
  [[../webpages/my_interests.php][My General Interests]]
#+LaTex: }

  The next section you will want fill out is "General Interests". This
  page is where you can provide information pertaining to your
  interests, workshops or presentations you would like to pitch to us,
  who you would like to be on panels with, and/or who you want to
  avoid.  This is also the place to give us other information we
  should consider when creating this event's programming schedule.

  Some people find that it is best to fill out this section last,
  after completing all other parts of the panel sign-up process.  You
  should feel free to come back to it at the end.
* My Schedule
#+LaTeX: \label{MySchedule.php}
#+HTML: <A NAME="MySchedule.php" ID="MySchedule.php"></A>
#+LaTeX: \underline{
  [[../webpages/MySchedule.php][My Schedule]]
#+LaTex: }

  This page gives you your schedule for this event followed by your
  schedule and feedback from previous events.  It also has links for
  an ical (for your phone/tablet/computer calendar) and a printable
  schedule.  Your schedule should also be in your panelist packet.
* Contact

  There should be a contact email at the bottom of each page, if you
  need help or assistance.  Also, please reach out to your liaison at
  any time if you need more information, or anything.
