#+TITLE: Photo Lounge Flow in Zambia
#+EMAIL: NELA.Percy@gmail.com
#+AUTHOR: Percy
#+DATE: January 2016
#+MACRO: DESCRIPTION Zambia is a piece of Conference Management Software.  This document is a "How To" guide assisting in the way of keeping track of Volunteer Hours for the Zambia FFF-branch instance for your conference.  This is still a work in progress.
#+DESCRIPTION: Zambia is a piece of Conference Management Software.  This document is a "How To" guide assisting in the way of keeping track of Volunteer Hours for the Zambia FFF-branch instance for your conference.  This is still a work in progress.
#+MACRO: KEYWORDS Zambia, Documentation, FFF branch
#+KEYWORDS: Zambia, Documentation, FFF branch
#+LANGUAGE: en
#+OPTIONS: \n:nil ^:nil timestamp:nil creator:nil H:3 num:3 toc:nil @:t ::nil |:t -:t todo:nil tasks:nil tags:nil <:t *:t author:t email:t skip:nil d:t f:t pri:t
#+STARTUP: fninline
#+SETUPFILE: "Headers/setupfile.org"
#+INCLUDE: "Headers/include.org"
#+TOC: headlines 3
#+LaTeX: \newpage
#+LaTeX: \pagenumbering{arabic}
* Introduction

  The Photo Lounge is a complex addition to Zambia that might not be
  used by all groups.  Some groups have used it, some have not.  Like
  all optional pieces, this can simply be untouched, and un-setup, and
  it will not bother anyone.  On the other hand, if you wish to use
  it, and have the ability to host something like a Photo Lounge or
  Art Gallery or the like, this is the right place to be doing so.

* Basic Setup

  Like all sub-sections of Zambia, to activate this you have to make
  sure you have a number of elements in your con setup in place.
** PhaseTypes

   A pair of PhaseTypes included in your con.  They would be "Photo
   Voting (17)" and "Photo Submissions (18)".

   Toggling the Photo Submission Phase, adds and removes the inclusion
   of the link to propose yourself as a photo submitter (a public
   page, which writes to a file, we'll get to that later) and your
   standard login to include the photo submitting words in the login
   string.  It also allows for the photo submission pages to be
   active.

   Toggling the Photo Voting Phase, adds and remvoes the links or
   access to voting for those who are of the right permissions to
   vote.
** PermissionRoles

   The three permission roles associated with the Photo Lounge are:
   + PhotoSub
   + PhotoRev
   + SuperPhotoRev

   PhotoSub is pretty straight-forward.  It is for those who are
   allowed to submit photos.  If they have no other role, then their
   login will take them directly to the Photo Submissions page.  If
   they do have other roles with the event (like presenting or
   volunteering) it will add the tab to their tab bar.  If they have
   other super-roles, then, to access the Photo Submission tab, they
   have to be under the "Participant View" section of the website to
   be able to submit their photos.

   PhotoRev is for those folks trusted with the job of reviewing
   photos.  It should open to the appropriate welcome page, and have
   the Photo Review tab available to them.  That leads to the voting
   section so they can express their opinions on what might or might
   not be included in the Photo Lounge.  There are still some quirks
   around voting, and one can game the system, by voting multiple
   times.  This will have to be coded around at some point in the
   future.

   SuperPhotoRev allows one to be able to select the voted on pictures
   for the lounge, give people permission to be PhotoRev and PhotoSub,
   and has StaffView.  This might want to become more limited, if the
   Super doesn't have other powers, to limit their access and review.
   Also the Super should be able to toggle on and off the Phases, but
   that also is still a work in progress.
** ConRoles

   There is one con role that works with this, but that is the host of
   the Photography Lounge, so not directly relevant to this document.
   See the document on Lounge Hosts.
* Scripts

  There are two scripts that are useful/necessary to the well-running
  of the Photo Lounge Flow.  They are:
  + create_thumbnails.sh
  + create_imagination_files.sh

  The create_thumbnails.sh script does just that.  Creates the
  thumbnail files.  It should be run periodically on a host that has
  access to the files, and can run convert from the imagemagick suite
  of programs to make the smaller, and much more useful, thumbnail
  files.

  The create_imagination_files.sh script is a script that will pull
  all the accepted files into a directory so that the imagination
  software from http://imagination.sourceforge.net/ can be used to
  create the slideshow.

  Both are fairly straight-forward and simple, but useful.
* Files

  There is a possiblity you would want to tweak the values at the top
  of the PhotoLoungeSubmit.php file.  They are:
  + $minwidth=1200;
  + $minheight=1200;
  + $maxwidth=30000;
  + $maxheight=30000;
  + $maxfilesize=6000000;

  and they map to, the minimum width, minumum height (both must
  be more than), maxumum width, maximum height (both must be less
  than) and maximum file size (must be less than).
* Flow

  + The flow starts when the call for Photo Submissions begins.
  + The SuperPhotoRev either asks for the phase to be set, or sets the
    phase to open, so that people might either submit, or apply to
    submit.
  + If self-service selection is enabled, then anyone who has been a
    Photo Submitter before can self-select into having those
    permissions again, on their own.
  + Anyone can be migrated to be allowed to be a Photo Submitter,
    again by the SuperPhotoRev.
  + If it is desired to just set everyone who has before been a Photo
    Submitter, to have that bit set for this event (replacing $conid
    with the current conid, of course):
#+begin_src html :exports both :results silent
    SELECT
        DISTINCT concat("INSERT INTO UserHasPermissionRole VALUES (",badgeid,",41,$conid);")
      FROM
          UserHasPermissionRole
      WHERE
        permroleid=41;
#+end_src
  + The PhotoSubs then submit photos at the [[../webpages/PhotoLoungeSubmit.php][PhotoLoungeSubmit.php]]
    page.
  + Once the photos are all submitted or the SuperPhotoRev is done
    soliciting them, that phase should be closed, and the Photo Voting
    phase should be initiated.
  + This would be a good time to have the create_thumbnails.sh script
    run.  That will make sure that all the thumbnails are in place,
    before the next step.
  + Folks that either have self-selected, if self-service has been
    enabled, or have been selected by the SuperPhotoRev may now go and
    vote on all the pictures at the [[../webpages/PhotoLoungePictures.php][PhotoLoungePictures.php]] page
    or by going directly to the individual artist selections at the
    [[../webpages/PhotoLoungeVote.php][PhotoLoungeVote.php]] page.
  + Once sufficient pictures have been voted on, the voting phase can
    close.
  + The selection process, of the pictures that are voted on have
    several steps, some of which can go in various orders, to be
    determined by the SuperPhotoRev.
  + View and select which of the voted-upon sets of pictures should be
    included into the lounge at the [[../webpages/PhotoLoungeCollectVotes.php][PhotoLoungeCollectVotes.php]] page.
  + Using the contact sheet, get in touch with all the appropriate
    PhotoSub folks to let them know what was selected from the
    [[../webpages/PhotoLoungeContactSheet.php][PhotoLoungeContactSheet.php]] page.
  + If there are any changes, they can be managed from:
    - the same contact sheet - [[../webpages/PhotoLoungeContactSheet.php][PhotoLoungeContactSheet.php]]
    - the view of the voted on pictures - [[../webpages/PhotoLoungeCollectVotes.php][PhotoLoungeCollectVotes.php]]
    - the report that also has the same information, without the
      possible confusion of changing what was selected -
      [[../webpages/genreport.php?reportname=picturesubmiswvote][genreport.php?reportname=picturesubmiswvote]]
  + Once the photos are all selected, this is a good time to run the
    create_imagination_files.sh script so that there is a directory to
    pull the appropriate files from, and create the slideshow from.
* Using the imagination software

  + Create a new slideshow: VOB/576 HD, no rescale, background=black
  + Import the images from the directory created by the
    create_imagination_files.sh script (probably
    Local/$conid/Photo_Lounge_Accepted)
  + Select all the images, and set the slide duration to 5.
  + Select all the images, and set a random transition, to be
    modified.
  + Select the speed (4)
  + Go through and fix all the transitions
  + Add the appropriate music
  + Export to a VOB file
** File exerpt:

#+begin_src html :exports both :results silent
[slideshow settings]
video format=576
background color=0;0;0;
distort images=false
number of slides=75

[slide 1]
filename=/home/dkap/hcarperoot/Downloads/PhotoLounge/Anthelian_1_mg_7182a.jpg
angle=0
duration=5
transition_id=13
speed=4
no_points=0
anim id=0
anim duration=1
text pos=4
placing=0
font=Sans 12
font color=0;0;0;1;
font bgcolor=1;1;1;1;
#+end_src
* Convert VOB to mpeg/avi

  + ffmpeg -i FFF??_Photo_Lounge.vob -f avi -c:v mpeg4 -b:v 800k -g 300 -bf 2 -c:a libmp3lame -b:a 128k FFF??_Photo_Lounge.avi
  + cp FFF??_Photo_Lounge.vob FFF??_Photo_Lounge.mpeg
* Load onto Devices

  + Thumb Drives:  Pictures into Pictures, only the mpeg in Movies
  + Pi Devices: Everthing into local Pictures, mpeg into sub Movie diretory in Pictures.
