#+TITLE: Time Card Usage in Zambia
#+EMAIL: NELA.Percy@gmail.com
#+AUTHOR: Percy
#+DATE: March 2012
#+DESCRIPTION: Zambia is a piece of Conference Management Software.  This document is a "How To" guide assisting in the way of keeping track of Volunteer Hours for the Zambia FFF-branch instance for your conference.  This is still a work in progress.
#+MACRO: DESCRIPTION Zambia is a piece of Conference Management Software.  This document is a "How To" guide assisting in the way of keeping track of Volunteer Hours for the Zambia FFF-branch instance for your conference.  This is still a work in progress.
#+KEYWORDS: Zambia, Documentation, FFF branch
#+META: KEYWORDS Zambia, Documentation, FFF branch
#+LANGUAGE: en
#+OPTIONS: \n:nil ^:nil timestamp:nil creator:nil H:3 num:3 toc:nil @:t ::nil |:t -:t todo:nil tasks:nil tags:nil <:t *:t author:t email:t skip:nil d:t f:t pri:t
#+STARTUP: fninline
#+SETUPFILE: "Headers/setupfile.org"
#+INCLUDE: "Headers/include.org"
#+TOC: headlines 3
#+LaTeX: \newpage
#+LaTeX: \pagenumbering{arabic}
* Introduction

  Checking in and checking out people (including yourself) is an
  importnat part of how the conference runs.  It is important before,
  during, and after the conference, for tracking hours, to see who is
  overburdened and needs more help, who is underutilized, and, if the
  volunteers are rewarded, who gets what and how to keep track of each
  of them.  It also allows you to figure out your coverage issues,
  when you need more people, and when you need less.

* Self Check-In/Check-Out

  The Check-In/Check-Out system is fairly striaght-forward.  
** To Check In
#+HTML: <A HREF="../webpages/VolunteerCheckIn.php">VolunteerCheckIn.php</A>

   In the staff view (green tabs) you just have to select the
   "TimeCards" tab.  The default view you get at this point should
   have you listed as the "Volunteer:" to check in.  Simply click on
   the "Choose" button.  This will take you to the Check In page.

   If you are about to start working, as in, checking in now, simply
   click the button reading "Check in <YOUR NAME> now."  You are now
   checked in.  After you are done with your FFF work, follow the
   check-out procedure.

   If, instead, you started working a bit ago, and forgot to check
   yourself in, or you worked some time, not near a computer, and need
   to retroactively create your check-in/check-out records, simply
   enter the start time of the period you worked in the box labeled
   "Actual Start time for <YOUR NAME>:" The format for that is
   YYYY-MM-DD hh:mm:ss (A four digit year, a dash, followed by a two
   digit month, a dash, followed by a two digit day, a space, followed
   by a two digit hour, a colon, followed by a two-digit minute, a
   colon, followed by a two digit second (Yes, you need the leading
   zeros, if any of the values are less than 10.) to be correct.)
   NOTE: This is a 24 hour clock.  Noon is 12, Midnight is 00, 1pm is
   13, and so forth.  There is a defualut time (now) in there, so if
   it was ten minutes ago, it's really easy to adjust for.  Keeping
   time to the second is not necessary.  Depending on your conference,
   you might be rounding to the nearest larger chunk of time (15
   minute, half an hour, whatever is decided) anyway, so follow the
   conventions of your conference.

** To Check Out
#+HTML: <A HREF="../webpages/VolunteerCheckOut.php">VolunteerCheckOut.php</A>

   In the staff view (green tabs) you just have to select the
   "TimeCards" tab.  From here, select the "Check Out" link just above
   the box containing your name.  This will take you to the Check Out
   page.  The default view you get at this point should have you and
   the time you checked in listed as the "Volunteer:" to check out.
   Simply click on the "Choose" button.  If, somehow, you have more
   than one check-in instance, please work through each of them, to
   make sure your hours are accounted for.

   If you have just finished working, as in, checking out now, simply
   click the button reading "Check out <YOUR NAME> now."  You are now
   checked out.

   If, instead, you finished working a bit ago, and forgot to check
   yourself out, or you worked some time, not near a computer, and
   need to retroactively create your check-in/check-out records,
   simply enter the end time of the period you worked in the box
   labeled "Actual end time for shift starting at <YOUR START TIME>
   for <YOUR NAME>:" The format for that is YYYY-MM-DD hh:mm:ss (A
   four digit year, a dash, followed by a two digit month, a dash,
   followed by a two digit day, a space, followed by a two digit hour,
   a colon, followed by a two-digit minute, a colon, followed by a two
   digit second (Yes, you need the leading zeros, if any of the values
   are less than 10.) to be correct.)  NOTE: This is a 24 hour clock.
   Noon is 12, Midnight is 00, 1pm is 13, and so forth.  There is a
   defualut time (now) in there, so if it was ten minutes ago, it's
   really easy to adjust for.  Keeping time to the second is not
   necessary.  Depending on your conference, you might be rounding to
   the nearest larger chunk of time (15 minute, half an hour, whatever
   is decided) anyway, so follow the conventions of your conference.
* Other Volunteer Check-In/Check-Out
** Not scheduled people during, or anyone before or after the conference
** Expected people on their shifts during the conference
* Useful Reports/Pages
** VolunteerCheckIn.php
#+LaTeX: \label{VolunteerCheckIn.php}
#+HTML: <A NAME="VolunteerCheckIn.php" ID="VolunteerCheckIn.php"></A>
#+HTML: <A HREF="../webpages/VolunteerCheckIn.php">VolunteerCheckIn.php</A>

   This page is the check in page, it is accessable under the TimeCard
   tab on any of the staff (green tab) pages.
** VolunteerCheckOut.php
#+LaTeX: \label{VolunteerCheckOut.php}
#+HTML: <A NAME="VolunteerCheckOut.php" ID="VolunteerCheckOut.php"></A>
#+HTML: <A HREF="../webpages/VolunteerCheckOut.php">VolunteerCheckOut.php</A>

   This page is the check out page, it is accessable from most of the
   staff check in pages.
** genreport.php?reportname=myusefultimecardtabledump
#+LaTeX: \label{genreport.php?reportname=myusefultimecardtabledump}
#+HTML: <A NAME="genreport.php?reportname=myusefultimecardtabledump" ID="genreport.php?reportname=myusefultimecardtabledump"></A>
#+HTML: <A HREF="../webpages/genreport.php?reportname=myusefultimecardtabledump">genreport.php?reportname=myusefultimecardtabledump</A>

   This report is to check on your own hours.  It is to make sure you
   didn't forget to record any, or to see if you left yourself checked
   in at any time previous.
