#+TITLE: Vending Design Document
#+EMAIL: NELA.Percy@gmail.com
#+AUTHOR: Percy, Amanda, Rob, Iya
#+DATE: May 2017
#+DESCRIPTION: Zambia is a piece of Con Management Software.  This document is a guide to building the Vendor System for the Zambia FFF-branch instance.  This is still a work in progress.
#+MACRO: DESCRIPTION Zambia is a piece of Con Management Software.  This document is a guide to building the Vendor System for the Zambia FFF-branch instance.  This is still a work in progress.
#+KEYWORDS: Zambia, Documentation, FFF branch
#+MACRO: KEYWORDS Zambia, Documentation, FFF branch
#+LANGUAGE: en
#+OPTIONS: \n:nil ^:nil timestamp:nil creator:nil H:2 num:2 toc:nil @:t ::nil |:t -:t todo:nil tasks:nil tags:nil <:t *:t author:t email:t skip:nil d:t f:t pri:t
#+STARTUP: fninline
#+SETUPFILE: "Headers/setupfile.org"
#+INCLUDE: "Headers/include.org"
#+TOC: headlines 2
#+LaTeX: \listoftables
#+LaTeX: \listoffigures
#+LaTeX: \newpage
#+LaTeX: \pagenumbering{arabic}
* General Design
  This is a working guide on how the vending portion of Zambia will be
  designed/changed.  Some of it is already in place, some has yet to
  be built.  This guide should have all the relevant bits in it so
  that all the stake-holders can have their say, and we are working
  off of one document.

  NOTE: when there is a - or a + next to things, it's because I asked
  that as a question, or made a supposition, and it was answered (by
  Amanda) so, for now at least the - is my side of the conversation
  and the + is her side of the conversation.
* Database Design
** Perennial
   These are the current values that should be migrated to the Zambia
   values if they are not already set.  The latest entries will be
   considered cannonical.  The ones of these in CongoDump will be more
   or less fixed and (currently) take an act of Vendor Coordinator (or
   other back-end Zambia person) to update.  

   The ones of these in Bios can be updated by the
   Vendors. times_at_fff_untracked should also be fixed.  Not sure
   about vendor_type.  If their "DBA" name is different from their
   vendor_business_name then, that can go in the bio field.

   The logo submission has yet to be determined, but I figure it's
   going to be handled along the same lines as the picture that we
   use for Presenters.
*** id
    CongoDump.badgeid
*** vendor_address
    CongoDump.postaddress1 and CongoDump.postaddress2
*** vendor_business_name
    CongoDump.badgename, Bios - badgeid=id, biotype=name
*** vendor_city
    CongoDump.postcity
*** vendor_contact_email
    CongoDump.email
*** vendor_contact_name
    CongoDump.firstname, CongoDump.lastname
*** vendor_contact_phone
    CongoDump.phone
*** vendor_country
    CongoDump.postcountry
*** vendor_description
    Bios - badgeid=id,, biotype=bio 
*** vendor_state
    CongoDump.poststate
*** vendor_website
    Bios - badgeid=id, biotype=url
*** vendor_twitter
    Bios - badgeid=id, biotype=twitter
*** vendor_facebook
    Bios - badgeid=id, biotype=facebook
*** vendor_fetlife
    Bios - badgeid=id, biotype=fetlife
*** vendor_zipcode
    CongoDump.postzip
*** vendor_type
    - New? possibly a short list of possible with a mapping to the
      vendor?
    - Might also include "community table" as a type?  If this isn't a
      short list of pickable things, we might want to make another
      table field "vendor/community table" with allowable "V" or "C"
      as part of the enum.
*** times_at_fff_untracked
    The number of times they vended at the fff that we currently don't
    have in the database, so that the generated number below can be
    (more) accurately generated.  As we add more instances (as I find
    them) this should probably get adjusted, so it's not artificially
    inflated. 
** Annual
   Most of these have to either be created, or co-opted, since the way
   that it was being done before is too baroque and complicated.  Easy
   enough to simply make new tables, and resuse little bits, instead
   of trying to force everything into the other workflow, as we did on
   an "emergency" and "emergant" basis, originally.
*** id - varchar(15)
    linked to Participants.badgeid
*** conid - int(11)
    linked to ConInfo.conid
*** created - datetime
    - when applied I think?
    + CORRECT
*** digital_advertising - Y/N (enum)
    - y/n or $ or type? 
    - do they want it? or how much?
    +  JUST A Y/N
*** fff_sponsorship - Y/N (enum)
    - y/n or $ or level? 
    - will they sponsor us?
    + JUST A Y/N
*** print_advertising - Y/N (enum)
    - y/n or $ or type? 
    - do they want it?
    + JUST A Y/N
*** updated - timestamp
    - most recently updated, I believe
    + CORRECT
*** vendor_acknowledgement - varchar(25) (signature)
    - Vendor acknowledges ... something?
    + VENDOR ACKNOWLEDGES THEY AGREE TO OUR TERMS AND CONDITIONS -
      THIS SHOULD BE AGREED TO ANNUALLY 
*** vendor_additional_notes / additional_information - text
    - this might also want to be perenial as well, perhaps?
    + ANNUAL ONLY; THIS IS REGARDING REQUESTS (EX:  FUR ALLERGY, WALL,
      ETC)
*** vendor_amenities_foo - ?? (see also VendorFeatures)
    - A variety of possible fields?  How is this  used?
      - 6ft_table
      - corner_endcap
      - extra_badges
      - number_of_chairs
      - shared_electrical 8ft_tables
    +  RIGHT NOW IT'S SPLIT INTO MULTIPLE LINES WITH MULTI OPTIONS.  #
       OF TABLES, # OF CHAIRS, CORNER/END CAP, ELECTRICAL, EXTRA
       BADGES 
*** vendor_contract - varchar(5)
    - How is this used?
    + THIS IS INITIALS TO STATE THEY READ AND AGREE TO OUR TERMS ALREADY ABOVE
*** vendor_invoiced - Y/N (enum)
    - Were they invoced?
    + YUP
*** vendor_location - ??
    - Where we put them.
    + YUP
    - This might want to be slightly more complex, building, room, and booth-number
*** vendor_payment_adjustment - decimal(13,4)
    - Adjustments to the bill
    + YUP
*** vendor_payment_amount - decimal(13,4)
    - amount they paid, should match invoiced amounts
    + YUP
*** vendor_payment_received - Y/N (enum)
    - check box?
    + YES
    - default "N" or maybe blank?
*** vendor_preferred_space - ?? (see also VendorSpaces)
    - Where they would like to be put.
    + NO - THIS IS BOOTH SIZE (SINGLE, DOUBLE, ETC)
*** vendor_loadin_self_carry - Y/N (enum)
    - will they?
    - This should be Y/n, right?
    + YES
*** vendor_sponsorship_package  - ??
    - what package they wanted?  They actually bought?
    + THIS IS THE Y/N ABOVE
    - if this is redundant it should be removed.  If it is the same as
      what is in missing, below, then ... perhaps not so missing after
      all?
*** vendor_status / status - Denied/Approved/Accepted/Approved/Paid (enum)
    + STATUS
    + DENIED, APPROVED, ACCEPTED, APPROVED AND PAID
    - Approved is in twice?  Should it be 4, Denied, Approved,
      Accepted, Paid?  I'd also add "Proposed" or the like?
*** rejected_reason - text
    + KEEP, WOULD BE SUBJECT TO CHANGE UNLESS VENDOR IS BANNER
** Missing
   These are values that I think we need, that don't seem to actually
   exist anywhere else, and should probably be at least tracked, if
   not having several layers to them, so that they can be figured into
   things like costs, and historical data.
*** vendor_sponsor_level
    - This might be the vendor_sponsorship_package piece?
    - This might get more complex, depending on the offerings
*** digital_advertising_level
    - This might need to be a table of some sort, based on the
      offerings
*** print_advertising_level
    - This might need to be a table of some sort, based on the
      offerings
*** vendor_actual_space
    - single, double, room, etc. probably based on the same
      VendorSpaces/VendorHasVendorSpace etc.
*** vendor_location_requests
    - although this might be under vendor notes?
** Generated
   These values would not actually be stored anywhere, but generated
   for various purposes, from other information collected in the
   database, rather than simple values.  The Vendor Invoice Amount
   should also go along with the Vendor Invoice, which lists all the
   things they are paying for, and interfaces with our credit-card
   system.
*** vendor_invoice_amount - decimal(13,4)
    - Money
    + YUP
    - possibly a geneerated field, as opposed to a stored one, based
      on the varieties chosen in vendor_amenites,
      vendor_payment_adjustment, vendor_actual_space and others?
*** times_at_fff 
    - currently a freeform field, should probably be generated, with a
      special number that adds in, for (currently) untracked events.
    + SOUNDS GOOD
    - Base figure above in perennial
** Structture
   These are the proposed new tables or modifications to existing
   tables that the data will be collected in.  Mostly interesting for
   building purposes, but also for those curious on how things operate
   under the hood, because, I like sharing that way, as opposed to
   keeping things secret and cryptic.  Yes, I know it's called "code"
   because we didn't want you to know what it did, but ... 
*** Vendor Constants
    - Most of these (as listed) are already in the CongoDump table.
    - Two need their own table:
      - vendor_type
        possibly a short list of possible with a mapping to the
        vendor, so might be another table
      - times_at_fff_untracked - int(3)
*** Vendor Yearly Variables
    - Most just are, as specified in this table
    - Some might be cross-references to the other tables below, or be
      in the other tables entirely.
*** Vendor Features
    Probably just a tweak to this table, and might need to be a
    "standard set" and a "this year set" like BaseFeatures and
    Features does as well as BaseServices and Services does and a
    repurposing of "SessionHasVendorFeature" to
    "VendorHasVendorFeature"
*** Vendor Spaces
    Probably just a tweak to this table, and might need to be a
    "standard set" and a "this year set" like BaseFeatures and
    Features does as well as BaseServices and Services does and a
    repurposing of "SessionHasVendorSpace" to "VendorHasVendorSpace"
*** Vendor Location
    Might be it's own table, with conid (linked), badgeid (linked),
    building, floor, room (possibly linked), and booth_number, and
    then code around it so blanks just don't get reported (aka, if
    they are a room vendor, their booth_number might not be listed,
    but if there are several vendors in a room, it might be.)  This
    might also allow ties to maps, and possibly the redraw of maps.
*** Vendor Status
    Might want to be it's own table as a mapping, so searches, and
    display_order could be set.
*** Vendor Sponsorship Package/vendor_sponsor_level
    These three would need to be determined.
*** digital_advertising_level
    These three would need to be determined.
*** print_advertising_level
    These three would need to be determined.
** Still Unknown
   These are the variables that exist already in the other usage
   space, that I still don't have a handle on.  More explination would
   be very useful.
*** created_by - number
    - Not sure what this does?
    + I THINK IT"S VENDORS NAME VS. I UPDATED, ETC
    - So ... how should it be expressed/tracked?
*** ordering_count - number
    - Another random number?
    + YES
    - Should it be kept?  Removed, what is it's state?  What is it's
      purpose?
* Front End
** Available Pages
   This should be the comprehensive list of all the pages that either
   the vendors/community table folk need to interact with or those who
   manage them (the Div Head) needs to interact with.
*** Returning Vendor sign-in
    By number or email address.
*** Returning Community Table sign-in
    By number or email address.  Might simply be switched on one of
    the values in the vending type or on it's own value, and just have
    one place to go?  Since we are collecting pretty much the same
    information for them both?  Or should I be separating them out?
*** New Vendor proposal
    With a catch to see if they are already in our database, using
    their email address
*** New Community Table proposal
    With a catch to see if they are already in our database, using
    their email address
*** Returning Vendor/Community Table informational gathering
    This can be the same, although there might, again, be a slight
    difference bases on vendor/community table differences.  Also, we
    might want to present last? event's information as defaults, so
    they have to do less typing. Dealing with changes once the state
    has changed to "invoice generated" might require Vendor Div Head
    intervention.
*** Returning Vendor informational update
    This might not be necessary, based on the above page keeping what
    is set for this year as set.
*** Returning Vendor/Community Table Bio update
    Page that they can, at will? update their web or book information.
*** Invoice
    Not available until after both they are accepted (by Vendor
    Div Head), and they hit the "generate invoice" button, which
    probably should lock changes.  Once the invoice is generated, it
    should be fixed, and also payable.
    This will (of course) be a comprehensive list of everything they
    agreed to.  The invoice page should continue to be available after
    they paid, so there is a referece point to the services agreed
    to/paid for.
*** Ad Copy Submissions
    For those who have agreed to either digital or print ads, this is
    a place for them to upload/submit them.
*** Vendor Jury
    The page that all the proposed vendors, with certain bits of
    information (to be determined, since I've not seen that page yet
    in our current system) will be on for the Vendor Div Head to move
    vendors to either "Accepted" or "Denied".  Probably includes some
    vendor notes and the like, including "Denied Reasons" Also
    probably where any price adjustments happen to the invoice.  Maybe
    a grouping by Vendor Type, and leaving the ones already moved on
    from this in a different colour, so that those already accepted,
    and their type, will be shown for balance reasons.
*** Vendor Placement
    After the invoice is paid? Or perhaps slightly different, if there
    is those that have invoice exceptions allowing for the placement
    of vendors.  Probably should have the invoice amount paid, and
    invoice amount expected on this page, to verify that they are,
    indeed, all paid up.  Also the vendor type should show up here, as
    well, so that similars can either be grouped together, or spread
    apart, as per the decision of the Div Head. May also contain
    previous placements, or links to previous maps or something useful
    along those lines.
*** Administer Vendor
    Where any changes are made to the vendor information (both that
    they can change and that they can't) for creation/update by Vendor
    Div Head.
*** Vendor Welcome Letter
    Generate the (physical) welcome letter to the vendors
*** Vendor Email
    Generate (and send) various all-vendor communications
*** Vendor Badges
    Generate the Vendor Badges for printing purposes.
*** Vendor Tents
    Generate all the vendor "tents" to put on their tables, to mark
    their place.
*** Check-in/Check-out lists
    All of the vendors expected, so they can be ticked off the list
    when they get there, and, so that when they return whatever they
    have to return at the end of the night (tax forms, possibly?) can
    be ticked off again.
** Flow
*** Task List
    Task List element with the call for vendors is created, with the
    appropriate link.
*** Task List
    Task List element with the call for community tables is created,
    with the appropriate link.
*** Email
    Possible email from Vendor Div Head goes out reminding
    vendors/community tables when the call will open and close.
*** Phase Change
    At the appropriate time, the Con Chair or Zambia bitch open the
    call for vendors.
*** Email
    Vendor Div Head generates and sends email letting the
    vendors/community tables know that the call is open.
*** Vendors/Community Table folk apply
    They use either the returning or the new pages, select the
    appropriate features, sponsorships, and ads that they want, and
    make sure everything is as expected.
*** (If Rolling Acceptance) Jury
    If there is a rolling acceptantce of vendors and/or community
    tables, while the vendor call/community table call is open
    acceptances can roll out and then things can go forward.
    Otherwise ...
*** Phase Change
    At the appropriate time, the Con Chair or Zambia bitch close the
    call for vendors.
*** Jury
    The (rest of (if rolling acceptance is happening)) vendors and
    community tables get acceptance, which probably is an individual
    email from the Div Head, with any specific to them in information
    included, and an invitation for them to pay their invoice.
*** Invoice
    Vendors then (hopefully, magically, smoothly) pay their agreed-to
    invoices.
*** Ad Copy
    All paid for advertizing copy is generated by the vendors or
    community tables is submitted.
*** Placement
    Div Head (and anyone else that can be roped into helping)
    schedules the vendors to be put in the appropriate locations on
    the day of the event.
*** Email
    Final email goes out, with any instruction reminders and if there
    is a manditory vendor meeting, or the like.
*** Welcome Letter
    Welcome lettters generated and printed, possibly stuffed in an
    envelope or folder of some sort.
    This might include some form of their (electronically) signed
    contract, and maybe invoice highlights.  Definitely includes their
    placement information, and information on how load-in and load-out
    works, etc.
*** Badges
    Badges, the appropriate number for each vendor and community
    table, are printed, and possibly stuffed as above.
*** Wrist bands
    Are possibly stuffed as above.
*** Check-in/check-out lists printed
    So they are available on the day-of.
* Conclusion
  This should cover all the bits and pieces.  If I missed any, let me
  know so this document can be updated, and the system can be tested.
  Hopfully all will work, and this can go forth as The New Way.  Until
  we change it, again, in 2-3 years *grin*.
