INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (126,1,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (127,1,' is a NYC based artist, photographer, sculptor, educator; Japanese rope bondage and single tail whip fanatic, computer geek, and just has way too many hobbies. He has been in the NYC scene for about 8 years, and served 4 years on the TES board and was TES\'s webmaster for 7 years and was also a founding member of TEC at TES.\n\nHe has been involved for years both politically and artistically, creating works at Burning Man and other venues. His work varies from installations to performance art, both vanilla and fetish. Most recently his work was featured at Diesel Denim Gallery in SoHo NYC, where he created a Shibari rope window to highlight a photo series of their jeans by Japanese erotic photographer Araki. He was an expert witness on behalf of TES in the Barbra Nitke V. Ashcroft lawsuit against the DCMA.\n\nAs an educator he has given numerous presentations and classes on everything from rope bondage and Japanese rope bondage to canes and whips at TES , Bondage SIG at TES GMSMA, Black Rose(DC), Shibaricon, Leather Leadership Conference 7 in Boston, Leather Retreat, The Tannery(Philly), Passional (Phily), TES2000, Purple Passion, Silk at Bard College, Conversio Virium at Columbia, and WHAP at NYU.\n\nwww.washi-nawashi.com \ndov@washi-nawashi.com');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (128,1,' I am a physician practising in New England within a primary health care setting. As such I advocate heavily for  for safety within play scenes (in a reasonable way) and advocate for a relationship with your physician should things go really really wrong and even if they don\'t. \n\nThat said I\'m also an avid player and oft intense Dominant, described by friends in the lifestyle as persistently Dom. There\'s little I don\'t enjoy and little I won\'t try, given some bounds of reason. I am active in several groups and feel its important to support teaching and bring another generation of folk into the lifestyle. ');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (130,1,' has been a practitioner of the rope arts for nearly his entire life.  If you knew how old he is, it\'s really not that impressive.  He took his first plunge into the lifestyle as a young child, binding and suspending a catwoman action figure, and pretty much anything else he could wrap with string–– including himself.  He made his mark on the scene 2 years ago, under the wing of his mentor, Lord Percival.  Since joining, he has become very active in Boston and New York.  He is a proud Other Fucker and the secret overlord of BTNG. Along with rope, Trialsinner is an active fetish photographer, known for creatively capturing his explorations into kink.  The Fetish Flea was the first event he ever attended, and he is honored to be presenting. http://www.trialsinner.com');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (131,1,'is the Director of the pansexual Boston/Mass chapter of MAsT (Masters and Slaves Together.) He is a Dominant with abiding interest and considerable experience in areas including Authority/Power exchange as expressed in D/s and M/s relationships, bondage, training, behavior modification, and erotic hypnosis.');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (132,1,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (133,1,' is a mid-twenties self-described Buxom Brazen Bitch. An avid Costumer, she has become well known for her corsets, boots, and tattoos. Rarely seen at events in anything else, mostly ones of her own design and handcraft! For over 10 years and at many venues, she has touted the wonders of costuming, especially corsets and kilts, to any who would hear her. Her goals in life are to own a small zoo, a full size replica of the Guggenheim Museum in New York, and to fit every person in the world in a Corset and/or a Kilt. She can be found in the New England area and often travels to New York, Philadelphia, and Washington, DC.');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (134,1,' is a polyamorous hypnotic Dominant. In her out-of-scene life she is a certified hypnotherapist, specializing in working with expectant mothers and families. In the scene, she practices and teaches erotic and D/s hypnosis. She has more than two decades of experience as a hypnotist and is very extroverted and social. Don\'t hesitate to come by and say hello and ask questions! ');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (135,1,' has been active in the BDSM lifestyle for nearly 20 years. After establishing himself in the lifestyle he became a fetish performer in Goth and Fetish nightclubs throughout the East Coast. As a BDSM educator he has taught for groups including TIED, Tidewater Pride, CUFF, and Amatorius. National events he presented at include Black Phoenix\'s Winter Solstice, Albany Power Exchange\'s Summer Bash, and Floating World. In addition to teaching for BDSM groups he has also provided workshops and BDSM outreach for Sci-Fi, Fantasy and Anime groups at their national events.  He is an active member of Fallout and The Crucible, a charter member Crimson Phoenix, and helped to found and run Amatorius. He is also very active with the vampyre community and the establishment of several vampyre organizations. He has an extensive martial arts background, and a strong interest in Japanese culture. Ramirez is also a retired open professional ballroom dance championship finalist and ballroom adjudicator.');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (136,1,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (137,1,' has been shooting her evocative, intensely personal erotic portraiture in New York City for over 10 years. She has lectured at Seattle Erotic Arts Festival, presented for BDSM groups and events across the US and Canada, exhibited in several major US cities, and been interviewed for cable TV, radio, webcasts, podcasts and magazines. She currently assists for all of Midori\'s Rope Dojo® weekend rope bondage intensives.\nMichele is regularly published in Cupido (Denmark, Norway) and has been a Photography Associate for On Our Backs magazine. Book credits include:  On Our Backs Guide to Lesbian Sex (Alyson), Photo Sex (Down There Press), SECRET Fetish Photo Anthologies 2-6, The Mammoth Book of Illustrated Erotica and the Mammoth Book of Illustrated Erotic Women (Carroll & Graf). Her work has also appeared in numerous US and European fetish and erotica magazines, and as cover art for dozens of books.\n\nwww.photodiva.com\n mserchuk@photodiva.com');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (138,1,' is dedicated to using his years of experience in the bondage scene to help others enjoy their time in rope more safely and fully.  He has presented locally in NYC and for events around the country on rope bondage and on other SM scene related topics. DeLano is the Assistant Instructor for Midori\'s Rope Bondage Dojo® weekend intensives, and he co-moderates the Japanese RopeArt and the Shibari Enthusiasts Yahoo groups. He\'s also co-presented with Michele Serchuk on their photographic collaborations in bondage imagery.');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (139,1,', a dedicated regular of Fetish Fair Fleamarket and NELA fan. Frequent sightings of her from around the globe make us wonder if she ever sleeps or if she\'s cloned her self. A sex-positive activist, she\'s made an improbable career out of being the traveling sexpert. Don\'t miss the groundbreaking book "Seductive Art of Japanese Bondage" which first cracked open the mysteries to Westerners, the hot essays in "Wild Side Sex: The Book of Kink" and twisted dark science fiction in "Master Han\'s Daughter"\n\nLearn more about her projects at www.PlanetMidori.com \nFind her class in your area at www.FHP-inc.com and www.RopeDojo.com');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (140,1,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (141,1,' is a foot-fetishist and lifestyle dominatrix with experience in humiliation, corporal punishment, female supremacy and TPE play. Hailing from sunny California, now based in Boston, this young and vivacious blond hair, blue-eyed Domina is known for the unique way she combines her sweet-natured appearance and natural charm with her insatiable appetite for cruelty and unbridled sadism. She has lectured on a variety of BDSM topics since 2003. Presenting at such institutions as Harvard, RISD, and Brown University as well as Lifestyle venues such Black Rose, Fetish Fair Fleamarket, Leather Retreat and Kink in the Caribbean has garnered her respect in both the vanilla and kink worlds.  Founding the Kink Academy in 2007 has allowed her to reach an even broader audience in a more personal way with her particular form of kink positive sex education, helping couples and singles reach a deeper understanding as well as a heightened creativity in their personal perversions. www.PrincessKali.com');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (142,1,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (143,1,' has a lengthy involvement with the leather and BDSM community.  He is a member Delta International, Mama\'s Family, NELA, and The Leather Archives & Museum.  He is a past member of GMSMA.  Tim has worked as an educator for over 25 years in the health, human services, and personal service industries.  He has been an active member of the leather community for several years and has a broad range of kinky and non-kinky passions.  Tim is the bootblack at the Boston Ramrod and has done bootblacking in NY, MA, CT, CA, and IL.  Some of Tim\'s interests and activities have included providing bdsm education geared at gay/bi men, studying leather history, creating social networking opportunities, providing youth empowerment, and charitable fundraising.  Tim is a virgo, Meyers Briggs INTJ/INTP, single and available 46 year old gay man.  While tim is a versatile bottom he is capable of Topping with several activities when the need arises..<grin>');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (144,1,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (145,1,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (146,1,' is the founder and head of the Boston Toy Party (www.thebostontoyparty.com), a NELA special interest group providing ongoing kink education events and linking the community with the areas top BDSM vendor-artisans.\n\nShe has taught at several venues, including NELA\'s Fetish Fair Fleamarket, Kinky Con, the New England Dungeon Society\'s Bondage Club, and the Sissy Soiree. She\'s also a faculty member at Kink Academy (www.kinkacademy.com).  \n\nHer areas of focus include belt bondage, pervertables, gender identity, gender kink and rape fantasies. \n\nShe has participated in BDSM outreach events, including at the University of New Hampshire\'s Sex Fair. Renee also has served on the board of a nonprofit supporting lesbian, gay, bisexual, transgendered, queer and questioning youth.\n\nHer vanilla hobbies include high-octane activities like skydiving, hard workouts that pit mind against body, driving fast cars the way they were meant to be driven and listening to fantastic music on fantastic sound systems in the aforementioned vehicles. She also loves Hello Kitty, acrylic nails, shopping, superior interior design and video games.\n\nShe is transgendered, male-to-female, and has lived full time for several years. She is an editor at a daily newspaper and lives and works in New Hampshire. ');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (147,1,' is a Canadian born Boston based rope enthusiast who is also often seen in NYC and sometimes Montreal with his rope bag and camera in hand.\n\nWhen he was first learning to tie, he found great support from the rope community and now gives that same support back to others wanting to learn. \n\nHe organizes the monthly Boston Rope Group meetings (www.bostonrope.com), and runs www.beknotty.com, a portal for rope bondage information. \n\nVisit his blog at  www.riggerjay.com');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (148,1,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (149,1,' is the organizer of Bound In Boston, a rope bondage group with an emphasis on education and community building. He began his journey with rope bondage as a fetish photographer (www.EvidenceOfDesire.com), but quickly found that he enjoys participating in hot rope play as much as he enjoys photographing hot rope play.');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (150,1,' has over twenty years of experience in BDSM, which gives her insights into what makes bottoms and submissives tick. She enjoys helping people new to the scene find their way, giving them the benefit of her years in real-life D/s relationships as well as learning from others.  She believes that knowledge shared during frank discussion, combined with a sense of humor, provides valuable tools and techniques so that bottoms can learn how to safely enjoy the entire experience, with emphasis placed on the responsibility of the bottom and coping with physical and mental issues bottoms experience.   She is an opinionated, self-avowed bratty bottom who enjoys predicament play and rope bondage.  Owned and collared by Septimus, she is an incurable shoe slut and has a blog exploring her love of footwear, various D/s dynamics and her own D/lg relationship at nakedconfusion.com.  When not on Fetlife, she can usually be found tweeting up a storm under the name silverdreams.');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (152,1,' Do what thou wilt shall be the whole of the Law.\nBeth Kimbell aka Safety Penguin is an advocate for sexual freedom, a switch, a masochist, and an esotericist, based in Salem, MA. She loves the alt-sex community; manages an Aerospace/Defense R&D lab; practices magick; plays D&D; plans events for charity; organizes a biannual leadership seminar; caters the rare wedding; but spends most of her time reading, writing her next essay or ritual, or compulsively rearranging her home. She is a Thelemic Priestess, an Initiator, and a Senator in the O.T.O., a NELA volunteer and incoming Secretary, and a programming volunteer for Transcending Boundaries 2011.  Beth recently had the joy of presenting on at TBC 2010, presented How to Host a Party at Ramrod\'s Leather Expo Day of Education, sat on the Rainbow Spirituality panel as part of Salem State College\'s GLBT Week, and on two panels at FFF #34.  She likes things \'Just-So\' and idolizes Benjamin Franklin.\nLove is the law, love under will ');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (153,1,'\'s knot tying education started at the age of 4 by many ole salts who had been boating for more than 40 years. When he came out at 21, he started applying the knots to bondage, and it has been fun ever since. He considers his leather journey a life long pursuit. Scott has been active with NELA over the past few years, and decided to join the NELA board in 2007, and served as Co-Chair from 2007 to 2008.\n\nScott held the title of Mr. Boston Leather in 2004. In 2003, Co-founded the Bay State Marauders, and served as the inaugural President from 2004 to 2005, and Vice President from 2006 to 2007. In 2007, won the Pantheon of Leather New England Regional Award. In 2009, was elected to the National Board of Leather Leadership Conference.');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (154,1,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (158,1,' has been an animal role-player nearly all her life and as a pet play enthusiast she enjoys offering her take on entering the world of animal role-play and how to explore and nurture animal identities.  She is best known for starting the company Wolf Princess Designs, specializing in custom animal costumes and animal-inspired fetish gear.  Her philosophy: kink comes in a variety of colors, styles, and textures and play is an important part of a person\'s life, no matter what age.');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (159,1,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (161,1,' is the sex-work alias for an award-winning producer, director, choreographer, and writer who has been creating and performing since 2000, first in San Francisco, then in Boston.  In addition to her live performance work, Ms. Moore is a full-time phone sex operator, dirty-talk educator, and creator of a forthcoming line of custom and off-the-rack audio smut (heh heh, she said "rack").  <I>Little Black Book Productions</I> is the umbrella company for these endeavors.');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (162,1,' is a queer, ambitious, and nerdy kinkster who has been exploring BDSM for the last 10 years. She brings with her a love for life, a bad sense of humor, and a love for baking. Lauren has a vast range of interests that she is always exploring. The interests include bondage, power exchange, impact, and sexuality. The Lauren has an evil streak, and has been referred to as "deliciously sadistic", though she will always swear she is a sweetheart. Lauren loves to teach and interact within the scene. She has taught for the Fetish Flea, TiedUp!, Bound in Boston, TES and local NYC events. TheLauren - Accept no imitations. ');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (163,1,' I am a 23 year old graduate student with a kinky side that I didnt start  really exploring until the beginning of 2009. I am now an active member of the Boston and NH kink community, attending munches, play parties, and events around the Northeast. I organized NH Seacoast Kink last March 2009 to bring together like-minded people around the same age and location. I strive to learn more about the kink community and help educate others on the different perspectives of this lifestyle and guide them to a place where they can feel comfortable and at ease with their kinky side.');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (164,1,' is a bondage enthusiast from the Boston area.\nHe runs the Massachusetts Bondage Club which is a special interest\ngroup of the New England Dungeon Society. He has run the bondage lounge\nat the FFF for many years in the past. He loves straitjackets and roleplay.');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (165,1,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (167,1,' is a member of The Society, WMPE,  Femdom New England. I have been in the BDSM lifestyle for 2 years. I am a Switch who is collared but able to still enjoy Dominating at times. I am very involved with Femdom New England. I help organize events like munches.');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (168,1,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (169,1,' has been known as a Rennaissance Woman since high school, and that "must learn about everything" attitude has served her well in her six years in the BDSM scene.  Currently a RISD student in Comic and Sequential Art, her day job is a freelance photographer, graphic designer and illustrator for Haka Wholesale/bluexotics.com and other clients.  She draws, paints, photographs, does a variety of fiber art and leatherwork, and is working on becoming a polyglot.  Her biggest hobby is roleplaying, Werewolf: the Apocalypse and Changeling: the Dreaming are her favorite systems, though she dabbles in others.  Her favorite kinks include shapeshifter roleplay, animal roleplay (especially ponyplay), bondage, sensory deprivation, and the psychology of BDSM.  Let\'s do the mind warp again.');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (170,1,' has been involved in TNG in WMPE and The Society for years.');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (171,1,' is one of the members of the Boston TNG group.');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (172,1,' comes to us from the Sunny South, and has become associated with the New England FFF, through the Charlotte branch of the same.');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (173,1,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (174,1,' began exploring BDSM with his Master 14 years ago, after three years together as a vanilla gay couple. A profile of the couple appears in the book, Ask the Man Who Owns Him. Today he is a member and officer of the Bay State Marauders and of Delta International. He started the gay men\'s Boston chapter of Masters and slaves Together in 2000. Eric is also the creator of the (educational!) BDSM themed card game, Pig of the Run.');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (175,1,' is our Speed Dating/Speed Flirting/Speed Negotiating coordinator.');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (176,1,' is a former English teacher and casual student of science fiction who blames Robert Heinlein for first introducing her to open relationships. She enjoys balancing a June Cleaver-esque love of cooking from scratch and household management with a kinky/poly lifestyle all while holding down a job, taking classes and being involved in the larger community in ways she adores. As a former freshman English teacher, she has a keen understanding of power dynamics! Together with Darkteddybear, she has recently taught at numerous conferences and meetings, including Floating World, Western Mass Power Exchange and Conversio Virium and looks forward to the chance to share new ideas and perspectives and hear those of others about the overlap of sexuality and science fiction/fantasy.');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (178,1,' is our games coordinator.');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (179,1,' is well known for being the inspiration for a fetish for eating what she has baked, Mephki is one of the moving forces behind the throne of the NELA Hypnosis SIG.');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (180,1,' is the organizer and producer of the UVM: Upper Valley Munch.');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (181,1,' is a long-standing member (and organizer) of the Violet Wand Guild: Shocking People into Pleasure for Decades.');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (182,1,' is one of the organizers and staff members of The Floating World.  Come see the event this coming Summer!');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (183,1,' is active with the Society in Hartford, CT, where she hosts a monthly discussion group on polyamory/open relationships and BDSM.  She is proud to have been a co-chair for the 2009 Transcending Boundaries Conference (www.transcendingboundaries.org), and is glad to be serving as Content Coordinator and Secretary of their Board of Directors for 2010. She is a past presenter for the Western Massachusetts Power Exchange (WMPE), Arisia, and TBC, among others.  As a Little, she fluctuates between being a Big, a twelve year old know-it-all, and a four year old dangerously in need of a juice box.');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (184,1,' is the Assistant Chair Person for the 2011 Transcending Boundaries Conference (www.transcendingboundaries.org) in Springfield, MA.  He is a kinky, queer activist and head of a poly family and home.');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (185,1,' is the owner and operator of the New England-based kinky custom design shop Big Head Studio. He and his partner, Elle E., travel across the country teaching classes and running workshops on Alternative Adult Sex Ed. And BDSM. Scott has taught at events such as Black Rose and Dark Odyssey in D.C., T.E.S. and Floating world in N.Y., the Boston F.F.F., and many others. He has given workshops at various universities, including Brown, Columbia and R.I.S.D. His writing has appeared in Secret Magazine and other international publications.\n');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (186,1,' is a bi, poly, kinky, geeky, girly, subby, sort of gal.   She serves as treasurer on the board of Transcending Boundaries, INC, an education, activism, and support group for persons whose sexual orientation, sexuality, gender identity, sex, or relationship style do not fit within the binary confines of male or female, gay or straight, monogamous or single.   Aimee lives in western mass with her three partners, four cats, and one tiny dog.');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (187,1,' has been in the public scene for five years, and has served in the leadership for both WMPE and the Society. He has presented at numerous events/groups during the last three years, including student sex-positive groups, sci-fi cons and lifestyle events. He is proud to be part of the Transcending Boundaries staff, serving as Director of Operations for the third consecutive year. A graduate student at UMass Amherst, he lives with his chosen family in Western Mass.');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (188,1,' is an arts/nude, fetish-bondage and erotica model.');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (189,1,' is a Volunteer');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (190,1,' is a Volunteer');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (191,1,' is a Volunteer');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (192,1,' is a Volunteer');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (196,1,' is a Volunteer');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (197,1,' is a Volunteer');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (198,1,' is a Volunteer');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (199,1,' is a Volunteer');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (200,1,' is a Volunteer');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (203,1,' is a Volunteer');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (204,1,' is a Volunteer');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (205,1,' is a Volunteer');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (206,1,' is the fill in to hold the spot of the NELA based volunteers');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (207,1,' is an opportunistic, polyamorous, pansexual, kinkster, NaughtyEm relishes in finding new and creative ways to bind, torture, and please. \n\nNaughtyEm maintains a dynamic view of BDSM, approaching each experience with openness and sensitivity. Her receptivity and insight have earned her a reputation for enthusiasm and intensity on both sides of the D/s spectrum. Regardless of her role or the environment in which she plays, the most important aspect of every scene is the connection and bond she builds with her partners.\n\nA familiar face at New England Cons, NaughtyEm looks forward to presenting classes that will turn heads and leave minds naughty.');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (208,1,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (209,1,' has played a number of roles in her life, both literally as she earned her BA in Drama from Ithaca College, and figuratively as she earned her MEd from University of New Hampshire. Her most important role is currently as the owned slave of Jawn. She is also the Director of MAsT Mass (Masters And slaves Together), a monthly discussion and support group for those interested in pursuing power exchange relationships. With Jawn, she is Reverend Reacharound, an irreverent punk cabaret group. ');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (210,1,' is a Volunteer');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (211,1,' is a Volunteer');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (212,1,' is ... well ... hacksaw');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (213,1,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (214,1,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (215,1,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (216,1,' is a fun-loving rope geek and sex educator who has found a home in the Midwest kink community. When he\'s not traveling to events, he contributes to the Iowa State University CUFFS group, and serves on the board of Minneapolis TNG group Min-KY. Although he\'s a relatively new member of the scene, LqqkOut has presented at numerous events across the country, including Kinky Kollege, Shibaricon, Denver Bound, and Beyond Leather.\n\nAs a presenter, LqqkOut aims to provide a comfortable down-to-earth learning environment for all genders, orientations, and experience levels. ');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (217,1,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (218,1,' is a chicken.');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (219,1,' is a pro bondage rigger, model, director, rope maker and body mod enthusiast. Active in both professional and private BDSM community since her start in 2001, she has been a prominent kink positive face in the adult industry. From Vanity Fair magazine, Insex, former House of Gord resident, Kink.com\'s pornglomerate Guest Director/Rigger/Top, Adam & Eve\'s Instructional Bondage Guides, former head piercer of the LA Chapter of CoRE, and of course her own site, ClaireBondage.com, she has some interesting bondage insight.\n\nAs a lover, player, rigger, collared slave and lots of things in between, her love of intense bondage encourages her to test both her physical and intellectual limits as much as possible especially with her current exploits as a handler for Intersec Interactive (formerly known as Insex.com). Experimenting with everything she could get her hands on from circus school to rope crafting she hopes to provide a zany but unique BSDM perspective from her play style!\n\n\n\n \n\t\n\n\nClaire Adams\n\nClaire Adams is a pro bondage rigger, model, director, rope maker and body mod enthusiast. Active in both professional and private BDSM community since her start in 2001, she has been a prominent kink positive face in the adult industry. From Vanity Fair magazine, Insex, former House of Gord resident, Kink.com\'s pornglomerate Guest Director/Rigger/Top, Adam & Eve\'s Instructional Bondage Guides, former head piercer of the LA Chapter of CoRE, and of course her own site, ClaireBondage.com, she has some interesting bondage insight.\n\nAs a lover, player, rigger, collared slave and lots of things in between, her love of intense bondage encourages her to test both her physical and intellectual limits as much as possible especially with her current exploits as a handler for Intersec Interactive (formerly known as Insex.com). Experimenting with everything she could get her hands on from circus school to rope crafting she hopes to provide a zany but unique BSDM perspective from her play style!\n\nTo learn more about Claire, visit ClaireAdams.com and ClaireBondage.com');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (220,1,' is an internationally recognized and award winning Bondage Rigger, Director, Producer, Rope Artist, Master/Dominant/Owner, BDSM Educator, Rope Maker, Dominant of SlaveToBondage.com, and handler for Intersec Interactive (formerly known as Insex.com). Damon is a perpetual student and lover of bondage. He has studied rope bondage and other forms of restraint in the USA and in Japan since the early 90\'s. His love of restraint also inspired him to create his rope company, VintageRope.com with Claire Adams. His work can be seen in places like Dave Naz\'s LA Bondage book, to the erotic work of Andrew Blake, rock videos, and hundreds of publications and numerous appearances in adult BDSM. ');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (221,1,' Ninja Sex Poodle & Ronin of Love, comes from the venerable rope bondage tradition of Madison, WI, where he honed his craft to become the world premiere podcaster of rope bondage with "the Ropecast".    He is the author of three novels including Nawashi (which climbed to #1 on the Podiobooks.com charts) as well as numerous short stories and essays. Graydancer\'s  writing has been published in several anthologies edited by Rachel Kramer Bussel, Secret Magazine, Power Exchange Magazine, and most recently "Ropes, Bondage & Power" (edited by Lee Harrington).');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (222,1,' believes that the magic of BDSM comes through the physical and spiritual connection of the participants. And while his workshops develop and nurture that connection, he always maintains a decidedly sadistic edginess. Scott\'s reputation for teaching some of the most spectacular kink classes in the U.S. is most certainly earned and well-deserved.\n\nStarting in the early 90\'s, he has presented countless sadomasochistic workshops and seminars throughout the country for organizations including: Chicago Hellfire Club, GMSMA, Leather University, C-Space, Living in Leather, OCLA, Sampler, Inferno, Thunder in the Mountains, Black Rose, Journeyman Academy, Orlando Bash, UPEX, Shibaricon, Southplains Leatherfest and various international venues. Scott is an active member of Chicago Hellfire Club, has received a number of awards, and is incredibly honored to be a recipient of the Chicago Hellfire Club\'s Caligula award.Scott Smith grew up in the Northwest and began exploring the facets of S&M at an early age. With his creative and rather deviant mind, he enthusiastically developed his techniques of rope bondage and suspension from his experience with nautical and high angle rope work. The powerful physical interactions that became the hallmark of his S&M activities were initially necessities for various activities including white water rafting, scuba, climbing, and paramedical rescue.');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (223,1,' (Pedular Enthusiast Ticklee Extraordinaire) has been a long-time tickling enthusiast, a proud (and skilled) foot fetishist and a member of bdsm and tickling communities, on-line for 13 years and off-line for 10 years. P.E.T.E. co-presented "Beyond Feathers: Tickling 102", a highly successful tickle demo class at the NELA 2008 Winter Fetish Fleamarket.  He has since taught classes at Ramrod in Boston and two of the first classes to be taught at Club Hell in Providence, RI for their wednesday fetish night series.  P.E.T.E. is also an instructor for the Kink Academy and has a number of instructional videos on their website.  He co-facilitated numerous tickle play events for Tickle New England!, a yahoo group/community that he created to help organize and provide information and support for the New England tickle community (he regularly and politely turns away applicants from all over the world outside of New England who find the TNE! mixture of social support and playful connection very attractive).  P.E.T.E. has introduced tickling to many newbies, novices and interested parties, sometimes, joyfully, finding himself tied and tickled at the odd and sundry bdsm event.  P.E.T.E. is never far from his day-bag, complete with a few lengths of sturdy rope and a pair of fuzzy, nylon wrist/ankle cuffs just in case someone needs an emergency tickle session.  One of the most willing and highly ticklish Lees (ticklees) you will ever find, P.E.T.E. is also a highly-skilled and devious Ler (tickler), relentless in his application of mind-games and tickle play, adept at finding new tickle spots on people that didn\'t think they had any, inventing new ways of tickling others (and himself) with the most unexpected every day, household items.  He does most of his shopping for tickle implements at his local drug store.\n\n\tP.E.T.E. is also highly interested in exploring the healthy (physically, emotionally and spiritually) and therapeutic side benefits of tickling and laughter and is currently working to incorporate it into his work as a practitioner of various healing modalities. \n\n\tP.E.T.E. embraces tickling as a fun, sensual and erotic practice that holds great and dynamic benefits for those who practice it with openness, honesty and consensual integrity.  Tickling is a practice that just about anyone can be involved in with just about anyone else.  He has experienced the deep bonding that tickling brings to couples, friends and communities and seeks to share it with more and more willing and playful people in the New England area and beyond.  \n \n       P.E.T.E. and Tickle New England! are available to organize and facilitate tickle events, gatherings, parties, classes and FUNdraisers.  \n\nContact P.E.T.E. at footplay210@yahoo.com or on fetlife, footplay210.\nhttp://groups.yahoo.com/group/ticklene/\n\n');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (224,1,' has over 35 years of experience in BDSM and was one of the early pioneers and builders of the BDSM community in the San Francisco area. He continues to be heavily involved, both in his local area and nationally, as an SM author, educator, mentor, workshop leader, video producer, expert witness, and activist. Noted for being both an exceptionally knowledgeable and highly entertaining presenter, he is very much in demand and has presented on various aspects of relationships and sexuality in more than 50 cities in the United States and Canada. In 2007, Black Rose presented him with the Vaughn Keith National Educator Award.\n\nJay is the author of the frequently recommended book "SM 101: A Realistic Introduction" and the founder of the publishing company that later became Greenery Press. His book, "Jay Wiseman\'s Erotic Bondage Handbook" is widely hailed as the book that sets the standard of fundamental knowledge for this practice. His instructional videos on rope bondage are excellent resources for both beginners and experienced bondage practitioners. ');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (225,1,' Needs to Add Biography Here!');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (226,1,' for some reason thinks that this bio has been deliberately left blank.');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (227,1,' "Jocks only think about sports, nerds only think about sex" DrSlashBlight has been a kinky nerd his entire life. In his early days he would often day dream of kinky fantasies, but now he lives them. In Feburary 2009 he jumped into the public scene spreading the excitement of his favorite fetish, Hypnosis/Mind Control. Then he Co-founded the New England Hypnosis Group with fast friend and fellow Hypno-fetishist mephki. He can be found at play parties huddled in a corner whispering in the ear of a pretty girl, or Co-Topping with his Partner in Crime mad_patter. If you ever have a Hypnosis Question, D&D question, want to be Hypnotized, or want Zombie Survival advice, just ask DrSlashBlight… but you can call him Buddy.');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (228,1,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (229,1,', Co-founder of BTNG ("beating"), Boston\'s Young & Kinky, Solipsistic has been an active member of the Boston kink scene for several years.  His kink interests focus on activism, D/s dynamics, and providing proper discipline for naughty girls.');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (230,1,' is part of the BTNG Triumverate');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (231,1,' is part of the BTNG Triumverate');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (232,1,' is a Programming Volunteer');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (233,1,' is a Programming  Volunteer');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (234,1,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (235,1,' is world-renowned for teaching in the bottom-up methodology.');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (236,1,' is a long proponent of D/s in the New England Area, is also the moderator and organizer of the New England D/s mailing list.');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (237,1,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (238,1,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (239,1,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (240,1,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (241,1,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (242,1,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (243,1,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (244,1,' is The Floating World representative.');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (245,1,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (246,1,' is the Leader of the Fleadom Trail');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (248,1,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (249,1,' has a long history of community organizing and activism and has brought all\nthose years of experience in the vanilla community to NELA. Involved in the\npublic leather scene for 10+ years, she volunteered for NELA events before\njoining the board. As one of the original organizers of the Kaleidoscope Munch,\nshe continues to co-host what she hopes will become a successful munch/social\noutlet for leather People of Color in the New England area.');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (250,1,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (251,1,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (252,1,' has been involved with the scene since 2000, and is involved with The Society and sci-fi going-ons in the northeast.  Miss Kasi enjoys messy play & pet-play, and a variety of fetishes, and especially lots of Gothic, fetish, and fantasy costuming!');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (253,1,'is visiting us from England to bring that special foreign twist to what we do locally. She works with animals, is an artist and cosplayer, as well as a devotee of the splosh/wam fetish, kittenplay and gothic fetish clothing (especially pvc!).\nShe is active in the fetish communities both in England and the US, being an attendee to a number of fetish clubs as well as having given presentations to The Society (CT) and NELA. \nShe has been a regular at the winter FFF events since 2000, where she can usually be found helping local fetish vendors.\nGive her a saucer of milk and she\'ll love you forever! xx\n');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (254,1,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (255,1,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (256,1,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (257,1,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (258,1,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (259,1,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (260,1,' is Kyle\'s ~*Lover*~');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (261,1,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (262,1,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (263,1,', she\'s kinky');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (264,1,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (265,1,' is a walk in Volunteer');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (266,1,' is a Volunteer');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (267,1,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (268,1,', I\'m the one.');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (269,1,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (270,1,'');
