INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (1,3,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (100,3,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (120,3,'This is a test, this is only a test of the automatic biography testing system.  I need to generate more than 250 characters for this test to succeed, so I am going to go on at length, and breadth and see how far I can get, just in case I decide to.');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (122,3,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (123,3,' has extensive experience in many body/mind disciplines and has been teaching for decades. She co-founded MAsTMass, runs The Submissives\' Round Table, and is Speaker Liaison for NELA. Find out more at bendyogagirl.com – Because Flexy is Sexy.');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (126,3,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (127,3,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (130,3,', Rope artist, sadist, mindfucker, deliciously evil polyglamorous asshole from Boston. Secretly a switch. Shh.');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (131,3,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (134,3,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (135,3,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (136,3,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (140,3,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (141,3,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (142,3,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (144,3,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (145,3,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (146,3,' heads the Boston Toy Party. She has taught at the Flea, Kinky Con and other venues, and is on Kink Academy\'s faculty. She also has served on the board of an LGBT nonprofit. She is transgendered and works as a journalist in New Hampshire. ');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (147,3,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (148,3,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (149,3,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (150,3,' is an opinionated, self-avowed bratty bottom who enjoys predicament play and rope bondage.  Owned and collared by Septimus, she is an incurable shoe slut and has a blog exploring various D/s dynamics at nakedconfusion.com.  ');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (152,3,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (153,3,'- NELA\'s Director of Community Relations, Co-Chair 07-08. Mr. Boston Leather 04, Bay State Marauders Co-founder, President 04-05 VP 06-07. Pantheon of Leather New England Regional Award winner 07. National Board of Leather Leadership Conference 09.');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (154,3,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (159,3,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (161,3,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (162,3,' is a queer, ambitious, edgy, sadistic, and nerdy kinkster who loves to bake.  She enjoys bondage, power exchanges, blood, impact, and the mind-fuck. Lauren has taught for the Fetish Flea, TiedUp!, Bound in Boston, TES and local NYC events. ');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (163,3,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (167,3,' is a member of The Society, WMPE,  Femdom New England. I have been in the BDSM lifestyle for 2 years. I am a Switch who is collared but able to still enjoy Dominating. I am very involved with Femdom New England. I help organize events like munches.');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (169,3,' is an artist, scholar, and polyglot who is an avid roleplayer and a student of Comic and Sequential Art at RISD.  Keenly interested in roleplaying and the psychology and philosophy of BDSM, she loves losing herself in the labyrinth of the mind.');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (179,3,' is well known for being the inspiration for a fetish for eating what she has baked, Mephki is one of the moving forces behind the throne of the NELA Hypnosis SIG.');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (180,3,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (183,3,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (184,3,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (186,3,' is a bi, poly, kinky, geeky, girly, sort of gal.   She serves as treasurer on the board of Transcending Boundaries, INC.   Aimee lives in western mass with her three partners, four cats, and one tiny dog.  ');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (187,3,' has served in the leadership for WMPE and the Society. He has been a presenter for 3 years, appearing at a wide variety of events. He is proud to be on the Transcending Boundaries staff, serving as Director of Operations for the last 3 years. ');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (192,3,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (198,3,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (199,3,' is a Volunteer');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (204,3,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (207,3,' is an opportunistic kinkster, she enjoys finding fresh, creative ways to bind, torture, and please. Her perception and insight, combined with warm enthusiasm and sincerity, have earned her a fierce reputation on both sides of the D/s spectrum.');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (208,3,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (209,3,' has earned her BA in Drama from Ithaca College, and her MEd from University of New Hampshire. Currently as the owned slave of Jawn, and the Director of MAsT Mass. With Jawn, she is half of Reverend Reacharound, an irreverent punk cabaret group. ');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (210,3,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (213,3,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (214,3,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (215,3,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (216,3,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (218,3,' is a chicken.');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (219,3,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (220,3,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (222,3,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (223,3,' has taught numerous tickle classes for NELA and for groups such as NED/s, WMPE and the Society and is an online instructor for the Kink Academy. He is the creator of Tickle New England!.');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (224,3,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (225,3,' did not add SHORTER Biography here!');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (226,3,' thinks that this bio was deliberately left blank.');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (227,3,' is an Evil Hypnotist with a Heart of Gold who is a Gentleman that isn\'t Gentle.  Co-Founder of the NewEngland Hypnosis Group, BTNG Greeter, and one of the shining faces in the Boston Kinky Community.');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (228,3,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (229,3,', Co-founder of BTNG ("beating"), Boston\'s Young & Kinky, Solipsistic has been an active member of the Boston kink scene for several years.  His kink interests focus on activism, D/s dynamics, and providing proper discipline for naughty girls.');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (230,3,' is part of the BTNG Triumverate');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (231,3,' is part of the BTNG Triumverate');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (232,3,' is a Programming Volunteer');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (233,3,' is a Programming Volunteer');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (234,3,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (235,3,' is world-renowned for teaching in the bottom-up methodology.');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (236,3,', a long proponent of D/s in the New England Area, is also the moderator and organizer of the New England D/s mailing list.');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (237,3,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (238,3,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (239,3,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (240,3,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (241,3,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (242,3,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (243,3,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (244,3,' is The Floating World representative.');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (245,3,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (246,3,' is the Leader of the Fleadom Trail');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (248,3,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (249,3,' has a long history of community organizing and activism and has brought all\nthose years of experience in the vanilla community to NELA.');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (250,3,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (251,3,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (252,3,' has been involved with the scene since 2000, and is involved with The Society and sci-fi going-ons in the northeast.  Miss Kasi enjoys messy play & pet-play, and a variety of fetishes, and especially lots of Gothic, fetish, and fantasy costuming!');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (253,3,'is visiting us from England to bring that special foreign twist to what we do locally. She works with animals, is an artist and cosplayer, as well as a devotee of the splosh/wam fetish, kittenplay and gothic fetish clothing (especially pvc!).\n');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (254,3,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (255,3,', after a long break, is pleased to be back and active\nin the kinky world once again. Alex holds the title of International\nMs Bootblack 2006 and taught locally and nationally on a variety of\ntopics during hir title year. Currently, Alex utilizes hir\nprofessional education for perverse purposes and favors play that\nopens the door to the dark places that scare us. When not being\nactively kinky, Alex lives, works, and creates art in Central\nMassachusetts.');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (256,3,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (257,3,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (258,3,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (259,3,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (260,3,' is Kyle\'s ~*Lover*~');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (261,3,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (262,3,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (263,3,'\'s Kinky');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (264,3,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (265,3,' is a walk-in volunteer');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (266,3,' is a Volunteer');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (267,3,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (268,3,' want\'s you to See the web for the full biography.');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (269,3,'');
INSERT INTO Bios (badgeid,biotypeid,biotext) VALUES (270,3,'');
