INSERT INTO Sessions (trackid,typeid,divisionid,pubstatusid,languagestatusid,title,pocketprogtext,progguiddesc,duration,estatten,kidscatid,signupreq,roomsetid,statusid,invitedguest) VALUES

(16,22,7,4,1,'Disability Assistance - 7pm Sat','You will be on call at the registration desk to coordinate issues and answer questions for people with disabilities.  Assistance may include reading the schedule for a print-impaired attendee, giving "appropriate and detailed directions to a class", arranging for an ASL interpreter for a class, or directing individuals to accessible bathrooms and other accessible facilities.','You will be on call at the registration desk to coordinate issues and answer questions for people with disabilities.  Assistance may include reading the schedule for a print-impaired attendee, giving "appropriate and detailed directions to a class", arranging for an ASL interpreter for a class, or directing individuals to accessible bathrooms and other accessible facilities.','02:00:00',1,1,0,12,2,1),
(16,22,7,4,1,'Disability Assistance - 11pm Sat','You will be on call at the registration desk to coordinate issues and answer questions for people with disabilities.  Assistance may include reading the schedule for a print-impaired attendee, giving "appropriate and detailed directions to a class", arranging for an ASL interpreter for a class, or directing individuals to accessible bathrooms and other accessible facilities.','You will be on call at the registration desk to coordinate issues and answer questions for people with disabilities.  Assistance may include reading the schedule for a print-impaired attendee, giving "appropriate and detailed directions to a class", arranging for an ASL interpreter for a class, or directing individuals to accessible bathrooms and other accessible facilities.','02:00:00',1,1,0,12,2,1),
(16,22,7,4,1,'Disability Assistance - 9pm Sat','You will be on call at the registration desk to coordinate issues and answer questions for people with disabilities.  Assistance may include reading the schedule for a print-impaired attendee, giving "appropriate and detailed directions to a class", arranging for an ASL interpreter for a class, or directing individuals to accessible bathrooms and other accessible facilities.','You will be on call at the registration desk to coordinate issues and answer questions for people with disabilities.  Assistance may include reading the schedule for a print-impaired attendee, giving "appropriate and detailed directions to a class", arranging for an ASL interpreter for a class, or directing individuals to accessible bathrooms and other accessible facilities.','02:00:00',1,1,0,12,2,1),
(16,22,7,4,1,'Disability Assistance - 6pm Fri','You will be on call at the registration desk to coordinate issues and answer questions for people with disabilities.  Assistance may include reading the schedule for a print-impaired attendee, giving "appropriate and detailed directions to a class", arranging for an ASL interpreter for a class, or directing individuals to accessible bathrooms and other accessible facilities.','You will be on call at the registration desk to coordinate issues and answer questions for people with disabilities.  Assistance may include reading the schedule for a print-impaired attendee, giving "appropriate and detailed directions to a class", arranging for an ASL interpreter for a class, or directing individuals to accessible bathrooms and other accessible facilities.','02:00:00',1,1,0,12,2,1),
(16,22,7,4,1,'Disability Assistance - 8pm Fri','You will be on call at the registration desk to coordinate issues and answer questions for people with disabilities.  Assistance may include reading the schedule for a print-impaired attendee, giving "appropriate and detailed directions to a class", arranging for an ASL interpreter for a class, or directing individuals to accessible bathrooms and other accessible facilities.','You will be on call at the registration desk to coordinate issues and answer questions for people with disabilities.  Assistance may include reading the schedule for a print-impaired attendee, giving "appropriate and detailed directions to a class", arranging for an ASL interpreter for a class, or directing individuals to accessible bathrooms and other accessible facilities.','02:00:00',1,1,0,12,2,1),
(16,22,7,4,1,'Disability Assistance - 10pm Fri','You will be on call at the registration desk to coordinate issues and answer questions for people with disabilities.  Assistance may include reading the schedule for a print-impaired attendee, giving "appropriate and detailed directions to a class", arranging for an ASL interpreter for a class, or directing individuals to accessible bathrooms and other accessible facilities.','You will be on call at the registration desk to coordinate issues and answer questions for people with disabilities.  Assistance may include reading the schedule for a print-impaired attendee, giving "appropriate and detailed directions to a class", arranging for an ASL interpreter for a class, or directing individuals to accessible bathrooms and other accessible facilities.','02:00:00',1,1,0,12,2,1);


